### ISSUE TITLE
[swagger doc]don't change query parameter name in doc

### ISSUE THREAD

**Issue by Diluka** [nestjsx/crud#101]
@zMotivat0r I noticed you changed parameter names, for example, from `filter` to `filter[]`.
In `expressjs`, `filter`, `filter[]` and even `filter[0]` are the same. In fact, the API has not changed. But the swagger will be export to mock service. These changes will cause the app that called the mock service to crash.

And I mentioned before in #79, these documents are very helpful for people new to crud. But it is a kind of redundancy for people who are already familiar with it. And English doesn't make much sense to people who don't speak English.

If we can control whether it is enabled or modified to become a summary description of the local language, it will make full use of it.

Now I am doing this. It's a bit of hacky.
https://gist.github.com/Diluka/8292fced132ff97aa6f04ed5e19a3155

**Comment by zMotivat0r** [comment]
@Diluka ok, mate
I'll add swagger overrides, also I think I gonna add some disable swagger options.

**Comment by zMotivat0r** [comment]
@Diluka I've fixed params names in query builder/parser. Also, I've fixed params names in Swagger.
Can we close this for now?
And I hope you'll find some spare time to add Swagger parametrization on enabling/disabling summary description. Won't you? :)

**Comment by Diluka** [comment]
new feature about swagger go to #79
