### ISSUE TITLE
Add Put Routes in CrudController

### ISSUE THREAD

**Issue by RobotScribe** [nestjsx/crud#107]
On my project, we use `PUT` to update entities and we would like to use this library to generate new routes.

Is it possible to add a method which would use a `PUT` routes in the `CrudController`.

As a side question, why did you chose to use `PATCH` routes to update entities over `PUT` ?

**Comment by Diluka** [comment]
- [`PATCH`](https://restfulapi.net/http-methods/#patch) means partial update.
- [`PUT`](https://restfulapi.net/http-methods/#put) means completely update or insert new one.

`crud` update record partially, so there is `PATCH`.
And I also know some clients doesn't support `PATCH` method.

**Comment by RobotScribe** [comment]
It is not possible to add `PUT`method ?
I can make a PR if you like.

**Comment by Diluka** [comment]
Considering compatibility and business scenarios, we also often use `PUT` to do `PATCH` at work. But this violates the definition of `RESTful`. @zMotivat0r Your call.

**Comment by RobotScribe** [comment]
In case you agree I created a PR : https://github.com/nestjsx/crud/pull/109

**Comment by zMotivat0r** [comment]
@RobotScribe as soon as my comments in that PR is resolved I'll merge. Thanks!

**Comment by zMotivat0r** [comment]
added in [4.1.0](https://github.com/nestjsx/crud/blob/master/CHANGELOG.md#410---2019-06-27)
