### ISSUE TITLE
The combination of `filter` and `or`

### ISSUE THREAD

**Issue by Darkein** [nestjsx/crud#110]
Hey there, thanks for your great job !
I wonder if it's possible to make a nested filter:
`WHERE ({filter} AND ({or} OR{or} OR ...)`

I have to filter a list from a list of ids, then I want to filter on some attributes, but from the same variable.

Do you know how If it's possible to do it ?

Thanks

**Comment by Diluka** [comment]
docs:
https://github.com/nestjsx/crud/blob/f3d3c58a4c5b03a46b84189ef34e21581d39aa5a/packages/crud/src/crud/swagger.helper.ts#L123

implements:
https://github.com/nestjsx/crud/blob/f3d3c58a4c5b03a46b84189ef34e21581d39aa5a/packages/crud-typeorm/src/typeorm-crud.service.ts#L198-L221

So far, only this combination has been implemented.

It would be great if you could make a PR to implement a feature that can freely switch between the two combinations.

**Comment by Darkein** [comment]
I can try to make a PR. How do you see this ? A new keyword? or a param to add somewhere ?

**Comment by Darkein** [comment]
maybe we could add this notion by using ',' in the filters, for exemple:
```
?filter[]='id||eq||1,id||eq||2'
&filter[]='firstname||cont||pie
```
will give 
```sql
WHERE ( id=1 OR id=2) AND (firstname LIKE '%pie%')
```

the inverse for OR:
```
?or[]='id||eq||1,id||eq||2'
&or[]='firstname||cont||pie
```
will give 
```sql
WHERE ( id=1 AND id=2) OR (firstname LIKE '%pie%')
```

And if we mix both:
```
?or[]='id||eq||1,id||eq||2'
&or[]='firstname||cont||pie
&filter[]=companyId||eq||5
&filter[]=teamId||eq||1,team2Id||eq||2 
```
we will have 
```sql
WHERE companyId=5 AND (teamId=1 OR team2Id=2) OR (( id=1 AND id=2) OR (firstname LIKE '%pie%'))
```

**Comment by Diluka** [comment]
Although it looks good, it will greatly increase the difficulty of parameter parsing. This is a very common query condition, but it is not so well handled by the current interface.
Don't forget this `type||in||A,B,C` which has `,` too

**Comment by Diluka** [comment]
How about using JSON array？
for example `filter=["teamId||eq||1","type||in||A,B,C"]`
parse the whole `filter` into JSON, if the result is `string` (or failed as a `string` too) means single condition using current method to resolve, if the result is `string[]` you know what to do. :)

I think even this is still not good enough. The format of such parameters is too complicated, although it can be nested using `JSON#stringify` to generate.

**Comment by Darkein** [comment]
> Don't forget this `type||in||A,B,C` which has `,` too
Yep I was thinking about it and I think we can handle it with regex, even if i'm not an expert.

It's up to you, which syntax you prefer

**Comment by Diluka** [comment]
How about introduce a new param `separator`?
for an extreme example (~~don't do this at home 🤣~~ )
`?separator=(✺ω✺)&filter=teamId||eq||1(✺ω✺)type||in||A,B,C&filter=companyId||eq||5`
will get
```sql
WHERE companyId=5 AND (teamId=1 OR type IN ('A','B','C'))
```

the default of `separator` is `undefined` or `""` anything falsely. so it will behavior like right now. 

the `separator` can not be `,`, `|` and any `operators`. use at your own risk ┓( ´∀` )┏

I don't like `,` to be `separator` because of I can zip it into query string but I can't unzip it easily.
`/(,)(?=\w+\|\|)/g` this has magic (\*/ω＼\*)

**Comment by Darkein** [comment]
alright, let's find a good separator :)

also I tried to create a PR but that's not s easy because almost every RequestQuery has to become RequestQuery[], and I think there is a lot of impacts (I don't know your project well enough)

So I think I will try to create a PR as exemple, but you will certainly have to edit it

**Comment by Diluka** [comment]
close due to #265 merged
