### ISSUE TITLE
Don't suport MongoDb 

### ISSUE THREAD

**Issue by douglasgc** [nestjsx/crud#13]
I realized by prototyping your solution that it does not support mongodb through TypeOrm.
Would it be too much work for me to implement it on mongodb? What would be your suggestion?

bye and congratulations

**Comment by douglasgc** [comment]
let me fix it, the typeorm does not support the Query Builder.

**Comment by zMotivat0r** [comment]
Do you want to implement it on your own? If so, I don't mind to see your solution. If it's OK, will merge it into the lib.
