### ISSUE TITLE
Entity select problem

### ISSUE THREAD

**Issue by Jack74r** [nestjsx/crud#135]
Hello,

I'm new to crud. I have a problem managing user passwords.
Before switching to crud I was using simple select: false and the password was not returned but with crud the password is always returned . Is that normal or am I doing it wrong? i try @Exclude() same issue .

```
  @IsNotEmpty()
  @Column({ select: false })
  password: string;

  @BeforeInsert()
  hashPassword() {
    this.password = crypto.createHmac('sha256', this.password).digest('hex');
  }
```

On the discord of nest, dylan give me a solution to solve the problem add interceptors.

```
+@UseInterceptors(ClassSerializerInterceptor)
@Controller('users')
export class UserController implements CrudController<UserEntity> {
    constructor(public service: UserService) { }
}
```

Thank

**Comment by zMotivat0r** [comment]
Hi,
Have you tried to add `exclude` to your CrudController `query` options?
https://github.com/nestjsx/crud/wiki/Controllers#exclude

**Comment by Jack74r** [comment]
Yes it's works fine.
Just add in @Crud
 query: {
        exclude: ['password'],
    }
