### ISSUE TITLE
Cannot load embedded entities

### ISSUE THREAD

**Issue by Diluka** [nestjsx/crud#138]
If there is an entity whose property is an embedded entity, then this property cannot be loaded due to a naming issue.

```sql
SELECT `Player`.`id`           AS `Player_id`,
        # other fields
       `Player`.`utmSource`    AS `Player_utmSource`, # this is manually add by `builder.addSelect(this['alias'] + '.utm.source');` only this is working
       `Player`.`utmSource`,
       `Player`.`utmMedium`,
       `Player`.`utmCampaign`,
       `Player`.`utmContent`,
       `Player`.`utmTerm`
FROM `pegasus_h5_player` `Player`
LIMIT 1
```

all columns are using default naming strategy.

BTW, `TypeOrmCrudService.alias`'s access modifier shall be `protected`

**Comment by zMotivat0r** [comment]
so this might help, right?
https://github.com/typeorm/typeorm/blob/a858de1f195d41aaffdeb8c10faa538dc1a15f5c/src/metadata/EmbeddedMetadata.ts#L40

**Comment by Diluka** [comment]
https://github.com/typeorm/typeorm/issues/4047
There are still some problems with it, and it can be postponed. This will also involve queries and other situations.

**Comment by LisaMabley** [comment]
Is anything happening with this? About to refactor some stuff but I thought it was worth checking ...
