### ISSUE TITLE
[Question] Why force the use of req :CrudRequest 

### ISSUE THREAD

**Issue by Jack74r** [nestjsx/crud#145]
Hello ,
I would simply like to use the TypeORmCurdService methods but most of the methods use a req:CrudRequest parameter .
What's the point, why is it necessary to be used? Crash if is null

https://github.com/nestjsx/crud/blob/82de0a22874df907537ae60ab0672d7d1d2ba7af/packages/crud-typeorm/src/typeorm-crud.service.ts#L83 
I just want to use : 

```ts
@UsePipes(new ValidationPipe())
    async register(user: UserEntity) {
  const errors = await validate(user);
            if (errors.length > 0) {
                throw new BadRequestException({ message: 'Input data validation failed', errors });
            } else {              
                return await this.usersService.createOne(user);
            }
}
```

Thank

**Comment by zMotivat0r** [comment]
>What's the point, why is it necessary to be used?

You can take a look at the `typeorm-crud.service.ts` and see why it's being used, don't you?
Here:
https://github.com/nestjsx/crud/blob/5f3aed5a05cfb20bd057aa15cc84c96ed2c68658/packages/crud-typeorm/src/typeorm-crud.service.ts#L84
And here:
https://github.com/nestjsx/crud/blob/5f3aed5a05cfb20bd057aa15cc84c96ed2c68658/packages/crud-typeorm/src/typeorm-crud.service.ts#L383-L387
Other words, it's used to add your path params into your DTO if you have a controller path that looks like this e.g. `/company/:companyId/users`.

Second, there is [wiki](https://github.com/nestjsx/crud/wiki/Controllers#adding-routes) describing how you can get a `CrudRequest` object. It's pretty simple and easy to do - just use this interceptor in your method `@UseInterceptors(CrudRequestInterceptor)`.

Third:
>I would simply like to use the TypeORmCurdService methods

I understand that but please keep in mind that this service was created to be used within a crud controller first, and thus it might not suit every personal requirement of every developer who wants to use it outside a crud controller but as a stand-alone service.
