### ISSUE TITLE
[crud-request] CondOperator's value is not match ComparisonOperator's definition

### ISSUE THREAD

**Issue by Diluka** [nestjsx/crud#148]
https://github.com/nestjsx/crud/blob/5f3aed5a05cfb20bd057aa15cc84c96ed2c68658/packages/crud-request/src/types/request-query.types.ts#L45

`CONTAINS = 'contains'` shall be `CONTAINS = 'cont'` to match `ComparisonOperator`

**Comment by Deejay-Ste** [comment]
Hi, there's another mismatch in this enum : 
https://github.com/nestjsx/crud/blob/5f3aed5a05cfb20bd057aa15cc84c96ed2c68658/packages/crud-request/src/types/request-query.types.ts#L42

It should be : 
`LOWER_THAN_EQUALS = 'lte',`
