### ISSUE TITLE
[Feature Request] Custom operators

### ISSUE THREAD

**Issue by Diluka** [nestjsx/crud#149]
This feature allow developers to define new operators.

### For example: 
1. define a new operator `json_contains` template 
```ts
(alias, values)=> `JSON_CONTAINS(${alias}, ${values})`
```
2. use like `filter=roles||json_contains||ROLE_A,ROLE_B`
3. generate 
```ts
andWhere('JSON_CONTAINS(roles, :roles)',{roles: JSON.stringify(roles)})
```

**Comment by joeybenenati** [comment]
Is there any plan to implement this? This flexibility would nice as I'm now forked and manually adding postgis operators as I need.

**Comment by rgolea** [comment]
@joeybenenati how do you add postgis operators? Can you share some code? I need to use `ST_DWithin` but I'm not really sure how. Can you help?

**Comment by rgolea** [comment]
@joeybenenati Wow! That was fast! Thank you very much!!! Maybe afterwards I can study the project better and do a PR to add new params.

**Comment by rgolea** [comment]
@joeybenenati could you help me with testing this feature out? I will also add tests but at the moment I would like to know that it works. (Please see #253 )

**Comment by joeybenenati** [comment]
@rgolea  sorry, I've since abandoned using this package for my current project. It's a great set of tools but I need a little more flexibility. I too had some trouble navigating and testing the project. I need to adhere to STAC API spec  but would also like to incorporate a json based api query language simlar to loopback 3.

**Comment by Diluka** [comment]
this validation(see below) is preventing custom operators. But we can reuse the built-in operators to change their behaviors. for example  https://github.com/nestjsx/crud/issues/150#issuecomment-582266070 changes `eq` and `in`

https://github.com/nestjsx/crud/blob/76dc6c2bc841a9b6fdc68b730aa87043f327117b/packages/crud-request/src/request-query.validator.ts#L68-L74

**Comment by rgolea** [comment]
@Diluka the PR I pushed would have fixed the problem (hopefully)

**Comment by prevostc** [comment]
If that helps, I was able to implement a custom operator by overriding `mapOperatorsToQuery` on the service

```
  protected mapOperatorsToQuery(cond: QueryFilter, param: any): { str: string; params: ObjectLiteral } {
    if (cond.field === "tags") {
      let str: string
      let params: ObjectLiteral = { [param]: cond.value }

      const field = this.getFieldWithAlias(cond.field)
      switch (cond.operator) {
        case "$cont":
          str = `${field} @> :${param}::jsonb`
          params = { [param]: `${JSON.stringify(cond.value)}` }
          break
        default:
          str = `${field} = :${param}::jsonb`
          break
      }
      return { str, params }
    } else {
      return super.mapOperatorsToQuery(cond, param)
    }
  }
```

This is a bit of a manual work, but it makes sense to override the service protected functions to add new functionality. Maybe all that is needed is a "Custom operator" section on the wiki.
