### ISSUE TITLE
[BUG] string Slug incorrectly parsed as Date if in a specific format

### ISSUE THREAD

**Issue by Bnaya** [nestjsx/crud#161]
I have a controller that looks like so: 
```
@Crud({
  model: {
    type: Product,
  },
  params: {
    id: {
      field: "id",
      type: "string",
      primary: true,
    },
  },
```
When GET ing product with id like so: `/api/products/product-123123`
The SQL query ends with:
```
WHERE `Brand`.`bt_brand_id` = ?) `distinctAlias` ORDER BY `Brand_bt_brand_id` ASC LIMIT 100 -- PARAMETERS: ["0122-12-31T21:39:06.000Z"]
```
When the ID format is not STRING-NUMBER, its all file.

I assume the lib has some heuristics, that are incorrect?
Maybe it's here:
https://github.com/nestjsx/crud/blob/3d3f60420072aec296207ecfa06a8f1cb0194f2e/packages/crud-request/src/request-query.parser.ts#L167

**Comment by Bnaya** [comment]
After additional debug, the issue is here:
https://github.com/nestjsx/crud/blob/3d3f60420072aec296207ecfa06a8f1cb0194f2e/packages/crud-request/src/request-query.parser.ts#L255-L260

Even tho the type is configured as string, this.parseValue parses it as Date.
 parseValue should get optional expected type, and only if it's not there, should fallback to heuristic parsing.

**Comment by Bnaya** [comment]
My Workaround:
```ts
// workaround for https://github.com/nestjsx/crud/issues/161
const m = require("@nestjsx/util/lib/checks.util.js");
const origIsDateString = m.isDateString;
m.isDateString = (v: any) => {
  if (typeof v === "string") {
    if (/^[a-z]+-[0-9]+$/i.test(v)) {
      return false;
    }
  }

  return origIsDateString.apply(m, [v]);
};
```

**Comment by sgrebnov** [comment]
Same issue

**Comment by Bnaya** [comment]
More up to date workaround:
```ts
// workaround for https://github.com/nestjsx/crud/issues/161
const m = require("@nestjsx/util/lib/checks.util.js");
const origIsDateString = m.isDateString;

// eslint-disable-next-line no-useless-escape
const datePattern = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2}(?:\.\d*)?)(Z|([+\-])(\d{2}):(\d{2}))$/;

m.isDateString = (v: any) => {
  if (typeof v === "string") {
    if (!datePattern.test(v)) {
      return false;
    }
  }

  return origIsDateString.apply(m, [v]);
};

```

**Comment by sgrebnov** [comment]
Looks like parameter should be escaped so it works correctly (string is passed as-is w/o attempt to be converted to date time); The following works for me:
``
?filter=someParam||cont||CG-7
->
?filter=someParam||cont||"CG-7"
``

**Comment by Bnaya** [comment]
I think its due to json.parse that is part of the pipeline
This behavior is not documented and i dont see why regular string wont work
