### ISSUE TITLE
Link to existing object in a POST request

### ISSUE THREAD

**Issue by frco9** [nestjsx/crud#163]
What's the recommended way to link a object to another existing  one during a POST request ? 
It's not working if I post the foreignKey id directly in the payload.

Furthermore, coming from Django DRF, I'd love to be able to perform something like that : https://www.django-rest-framework.org/api-guide/relations/#slugrelatedfield

=== 

I have the following schema:  Source -- oneToMany -->  Image 
The source model have a slug field. 

When I create a new Image I'd like to be able to POST the following payload: 

```
{
  (...)
  "source": "instagram",
  (...)
}
```

And to have the a new Image object created with the correct foreign key set. 

Any idea on how to implement something like that ?

**Comment by johannesschobel** [comment]
Hey  @frco9 , 
how about creating the relationship via the URL? E.g., if you add an image to a specific source, your URL for doing this, may look like this:
```
POST /base/path/:source/images --> 
POST /base/path/instagram/images
POST /base/path/facebook/images
POST /base/path/twitter/images
```

Consider another example.. You want to add a document to a specific customer, you would have a route like this:
```
POST /customers/4711/documents
```
where `4711` may be the ID to identify a specific customer.

Hope this helps!?

**Comment by johannesschobel** [comment]
oh yeah.. additional info..
if you use named params (see the `:source` in the example above) you can easily check, if the source in the URL is a valid source :)

**Comment by frco9** [comment]
Thanks ! 
Well indeed it can bypass my issue but, I found it not really usable for the API consumer. 
Moreover the consumer is going to use the bulk creation so it would require him to sort data and use multiple requests

**Comment by johannesschobel** [comment]
I don't think it is a bad design to have multiple requests. Even but companies (Google, Twitter, ...) make multiple requests, you need to properly "cut" your data in meaningful packages, however.

When splitting it in several calls, you may get the benefit that you have a much more expressive API..
