### ISSUE TITLE
[Feature Request] Support Active Record

### ISSUE THREAD

**Issue by Diluka** [nestjsx/crud#166]
`TypeORM` has two patterns, `Data Mapper` and `Active Record`.

`crud` currently supports only `Data Mapper`. `Active Record` is more simple pattern it shall be supported too.

It can **NOT** be done like this
```ts
constructor(){
  super(Entity.getRepository());
}
```

The `getRepository` will be working when `onModuleInit` calling. And now `TypeOrmCrudService` is using `repo` in `constructor`.

**Comment by zMotivat0r** [comment]
What is the practical usage of this since we encapsulate all interactions with the DB in `TypeOrmCrudService`?

**Comment by Diluka** [comment]
I thought about it, it is better to keep it like this.
