### ISSUE TITLE
Doesn't build on Azure

### ISSUE THREAD

**Issue by ntegral** [nestjsx/crud#167]
When using the @Crud({}).. The application no longer builds on Azure after adding the package to the project.

**Comment by ntegral** [comment]
I'm correcting this issue.  The application does build successfully on Azure however the warmup request takes too long to reply and the application therefore fails.  The mapped routing is appearing to take too long to respond.

**Comment by ntegral** [comment]
I figured out how to get this to work on Azure.

**Comment by zMotivat0r** [comment]
@ntegral Maybe you wanna share any particular knowledge about your solution so that other devs might find it helpful?

**Comment by ntegral** [comment]
I’m compiling the list of changes required to get this feature to work on Azure.  In the meantime, I’m reviewing the documentation for routing and resources but it doesn’t appear to be working?

For example get: /heroes/:heroId/perks doesn’t work? Any additional documentation on this?
