### ISSUE TITLE
[Question] Can I get data with relation is null

### ISSUE THREAD

**Issue by lalalalaluk** [nestjsx/crud#170]
i have two entity 

```
import {Entity, PrimaryGeneratedColumn, Column, ManyToOne} from "typeorm";
import {User} from "./User";

@Entity()
export class Photo {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    url: string;

    @ManyToOne(type => User, user => user.photos)
    user: User;

}
import {Entity, PrimaryGeneratedColumn, Column, OneToMany} from "typeorm";
import {Photo} from "./Photo";
```
```
@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @OneToMany(type => Photo, photo => photo.user)
    photos: Photo[];

}
```

http://localhost:3000/api/user?join=photo 
when I get this url, I can't get user data which relation photo data is null

I write the code below
```
        return this.repo
            .createQueryBuilder('user')
            .leftJoinAndSelect('user.photos', 'photos')
            .getMany();
```

I can get the user data which photo data is null
like below
```
{
  id:1,
  name:'test',
  photos:null
}
```

Is there any way I can get user data which phote data is null in typerom crud join?

thank you.

**Comment by Diluka** [comment]
#98 WIP
and you can do this for now
```ts
// @ts-ignore left join only
TypeOrmCrudService.prototype.getJoinType = function(s: string) {
  return 'leftJoin';
};
```

**Comment by lalalalaluk** [comment]
@Diluka  thank you

**Comment by biammsilva** [comment]
> #98 WIP
> and you can do this for now
> 
> ```ts
> // @ts-ignore left join only
> TypeOrmCrudService.prototype.getJoinType = function(s: string) {
>   return 'leftJoin';
> };
> ```

Where should I put this code? In the service that extends TypeOrmCrudService?

**Comment by Diluka** [comment]
@biammsilva anywhere before you actually use service. I suggest using it like a polyfill.

you can create a `patch.ts` file and `import './patch'` in the bootstrap file.
