### ISSUE TITLE
[Feature Request] paginate with pagination info

### ISSUE THREAD

**Issue by Diluka** [nestjsx/crud#18]
currently it returns list only. for paging, there needs more info like `total`.
see https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/domain/PageImpl.java or https://github.com/pagehelper/Mybatis-PageHelper/blob/master/src/main/java/com/github/pagehelper/PageInfo.java

**Comment by zMotivat0r** [comment]
Possible duplicate of #12. Closing this issue.

**Comment by zMotivat0r** [comment]
Shipped with v3.0.0
