### ISSUE TITLE
Seeing something weird with order of imports

### ISSUE THREAD

**Issue by dolphub** [nestjsx/crud#19]
Having a few issues starting with the example code outlined in the base readme.
It seems that when I import Crud before my entity in my controller I get a stack trace
```
TypeError: typeorm_1.Entity is not a function
    at Object.<anonymous> (\src\app\posts\post.entity.ts:3:2)
```
```
import { Crud } from '@nestjsx/crud';
import { Post } from './post.entity';
```

However, when I import Post entity before Crud it seems to work.
Additionally, when I try to POST { "content": "blah" } it returns with a 500 with stack trace
```
TypeError: Cannot read property 'createOne' of undefined
    at PostsController.createOneBase (\src\decorators\crud.decorator.ts:207:25)
```

Code:
Entity:
```
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity()
export class Post {
    @PrimaryGeneratedColumn()
    id: number;

    @Column({ length: 500 })
    content: string;
}
```
Controller

```
import { Post } from './post.entity';
import { Crud } from '@nestjsx/crud';
import { Controller } from '@nestjs/common';
import { PostsService } from './posts.service';

@Crud(Post)
@Controller('posts')
export class PostsController {
    constructor(private readonly postService: PostsService) {}
}
```
Am I missing something obvious?
Thanks!

**Comment by zMotivat0r** [comment]
@dolphub yeah, you should name your service as `service`
here is the example: https://github.com/nestjsx/crud/blob/master/integration/typeorm/src/companies/companies.controller.ts#L23

**Comment by dolphub** [comment]
@zMotivat0r Thanks for the fix, I am able to create / fetch (simple testing).
I still am not sure why the order of imports fails it, 
I actually pulled down the example you're referring to in the docs, but am unable to actually get it to run out of the box.  Says `CrudOptions` is has invalid types. Both `options` and `params` don't exist on the type definition of CrudOptions following through the `Crud` definition.

I pulled down the repo down actually to see if the swagger docs contained the model information and how it was configured.

Is there a tag or branch somewhere where I can see a working example?

**Comment by zMotivat0r** [comment]
@dolphub sorry, I've updated dependencies in the integration. Please pull and try again

**Comment by fwoelffel** [comment]
Hi @zMotivat0r,
I can confirm this issue (and my service is named `service` like it is shown in the documentation).

### Works

```js
import { Controller, Inject } from '@nestjs/common';
import { LabelEntity } from '../entities/label.entity';
import { LabelsService } from '../services/labels.service';
import { Crud } from '@nestjsx/crud';

@Crud(LabelEntity)
@Controller('labels')
export class LabelsController {
  @Inject(LabelsService)
  private service: LabelsService;
}
```

### Doesn't work

```js
import { Controller, Inject } from '@nestjs/common';
import { Crud } from '@nestjsx/crud';
import { LabelEntity } from '../entities/label.entity';
import { LabelsService } from '../services/labels.service';

@Crud(LabelEntity)
@Controller('labels')
export class LabelsController {
  @Inject(LabelsService)
  private service: LabelsService;
}
```

Here is the raised error (triggered during tests):
```
    TypeError: typeorm_1.Entity is not a function

      1 | import { PrimaryGeneratedColumn, Entity, Column } from 'typeorm';
      2 | 
    > 3 | @Entity()
        |  ^
      4 | export class LabelEntity {
      5 |   @PrimaryGeneratedColumn()
      6 |   id: number;

      at Object.<anonymous> (annotations/entities/label.entity.ts:3:2)
      at Object.<anonymous> (annotations/controllers/labels.controller.ts:3:1)
      at Object.<anonymous> (annotations/controllers/labels.controller.spec.ts:2:1)
```

**Comment by avatsaev** [comment]
Same here, version `3.2.0`

**Comment by jakobrosenberg** [comment]
Same on ``3.1.0``

**Comment by Bnaya** [comment]
I have a feeling its related to `tslib` and maybe jest stuff
Code from typeorm index.js:
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
// ...
tslib_1.__exportStar(require("./decorator/entity/Entity"), exports);
tslib_1.__exportStar(require("./decorator/entity/ChildEntity"), exports);
tslib_1.__exportStar(require("./decorator/entity/TableInheritance"), exports);
// ....
```

Code from crud index:
```js
"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
__export(require("./decorators"));
__export(require("./dto"));
__export(require("./constants"));
__export(require("./enums"));
__export(require("./module"));
//# sourceMappingURL=index.js.map
```

**Comment by DwayneH** [comment]
@Bnaya Tried to use tslib for exports but didnt resolve the issue. 

What did though was upgrading node to 10.16.0. For some reason exports from the Entity.js file in Typeorm returned an empty object which was resolved after upgrading.

**Comment by zMotivat0r** [comment]
@jakobrosenberg @avatsaev @fwoelffel are you guys still having this issue with version 4?

**Comment by ymoreiratiti** [comment]
> @dolphub yeah, you should name your service as `service`
> here is the example: https://github.com/nestjsx/crud/blob/master/integration/typeorm/src/companies/companies.controller.ts#L23

Worked for me.

P.S: The url of example has changed. 
https://github.com/nestjsx/crud/blob/master/integration/crud-typeorm/companies/companies.controller.ts#L32
