### ISSUE TITLE
Error: Cannot read property 'getMany' of undefined

### ISSUE THREAD

**Issue by MeMeMax** [nestjsx/crud#190]
Hi,

I am getting this error:

> [ExceptionsHandler] Cannot read property 'getMany' of undefined +14494ms
TypeError: Cannot read property 'getMany' of undefined
    at StockController.getManyBase (C:\git_wa\privat\myStocks\crud-test-repo\node_modules\@nestjsx\crud\lib\crud\crud-routes.factory.js:115:33)
    at C:\git_wa\privat\myStocks\crud-test-repo\node_modules\@nestjs\core\router\router-execution-context.js:36:29
    at process._tickCallback (internal/process/next_tick.js:68:7)

I got a pretty basic setup. Just one Feature Module which should use nestjsx/crud to setup all the routes.

Here is a example repo which reproduces the error:
https://github.com/MeMeMax/crud-test-repo

Does anyone have a idea why this happens?

**Comment by zMotivat0r** [comment]
https://github.com/MeMeMax/crud-test-repo/blob/b83064c68d7625618b94518ecc05abaa2e12c232/src/stock/controllers/stock.controller.ts#L14

Change `stockService` to `service` and it will work. Crud services must be provided in  controllers as a property name called `service`

**Comment by MeMeMax** [comment]
@zMotivat0r Thanks for your help. This should be documented as a Warning or a hint in the docs. Someone likes to have service names which reflect the service and might step into this pitfall.

**Comment by zMotivat0r** [comment]
@MeMeMax yeah, you're probably right. I'll be glad to see a PR from you, if you want :)

**Comment by darwinguz** [comment]
@zMotivat0r, are there any way to custom this name?
