### ISSUE TITLE
Swagger getMany query params wrong type on "filter" "or" "sort" "join"

### ISSUE THREAD

**Issue by DaVarga** [nestjsx/crud#196]
I experiencing some issues with the types of the getMany query params.
The types of `filter` `or` `sort` and `join` are reflected with `"type": "string"` where in my opinion they should have the type 
```
"type": "array",
"items": {
  "type": "string"
},
  "collectionFormat": "multi"
}
```

**Comment by Diluka** [comment]
since it's working nice. do you mean here?
https://github.com/nestjsx/crud/blob/b1f092477fc2fb8945858bf4e39726cd5544c53a/packages/crud/src/crud/swagger.helper.ts#L113-L120
`filter` is `string`. and it's a query param. so it can be repeat like `?filter=a||eq||1&filter=b||eq||2`.

**Comment by DaVarga** [comment]
Yes exactly. Sure it works, but it doesn't comply with the swagger spec. https://swagger.io/docs/specification/2-0/describing-parameters/#array

If you generate a consumer api out of the swagger.json you most likely end up with an api wich only accepts one filter parameter. Passing something like `a||eq||1&filter=b||eq||eq||2` might work, but it's not really nice.

I have tried to change the meta in swagger.helper.ts. That worked great. Also in the swagger interface you have separate input fields per parameter.

**Comment by chriszrc** [comment]
If I try 

```
a||eq||1&filter=b||eq||eq||2
```

The ampersand gets encoded, and doesn't get picked up at all. I agree that swagger should be updated to use collectionFormat = multi, then we manually click the swagger button to add more params-

**Comment by chriszrc** [comment]
Adding many filter params is very cumbersome this way in the text box:

user_id||eq||1&filter=region||eq||Poland&filter=year||eq||2012

And requires typing in &filter over and over again, the collectionFormat = multi is nicer, the UI provides an option to click a button and add additional form fields for each additional filter parameter
