### ISSUE TITLE
RequestQueryBuilder add brackets for join query

### ISSUE THREAD

**Issue by WazZro** [nestjsx/crud#216]
Why does builder add brackets to join query, if count of join more than 1? Example: `query.setJoin({ field: 'company' }).setJoin({ field: 'roles' })`
At the out we get `join[]=company&join[]=roles` and backend requestparser cant parse it, so it just ignores that
I didnt find any ability to disable this function, or I have missed something in configuration?

**Comment by Darkein** [comment]
nestjs understand better query params with brackets (and a lot of frameworks), it's a kind of a convention.
For example if you only have one param, it will not be able to understand if this param is an array or not and will throw an error.

just try with and without brackets, you will see ;)

**Comment by WazZro** [comment]
Maybe, it has to work so, but it doesnt.
I use nestjsx/crud in my backend project. User entity has several relations, such as company and roles and etc. Accordion to the documentation, to load the relations, i have to add 'join' to request in query: /api/users/1337?join=company.
With join: `{
  "id": 1337,
  "company": {
    "id": 100,
    ...
  }
}`
Without join:  `{
  "id": 1337,
  ...
}`

With several joins /api/users/1337?join=company&join=roles:
 `{
  "id": 1337,
  "company": {
    "id": 100,
    ...
  },
  "roles": [...]
}`

But if I add brackets to join, the relationships dont load /api/users/1337?join[]=company&join=roles:
 `{
  "id": 1337,
  "roles": [...]
}`
Doesnt matter I have several joins or once for brackets, join with brackets is missed on server side with decorator @ParsedRequest

**Comment by zMotivat0r** [comment]
@WazZro have you enabled `join` in your controller's options? [docs](https://github.com/nestjsx/crud/wiki/Controllers#join)
You need explicitly enable them.

**Comment by WazZro** [comment]
I'd not be able to make the request if I did not enable this.
```
@Crud({
  model: {
    type: UserDto,
  },
  query: {
    exclude: ['password'],
    join: {
      company: {},
      skills: {},
      roles: {},
    },
  },
  routes: {
    exclude: ['createManyBase'],
  },
})
export class UserController implements CrudController<UserDto> {...}`

**Comment by zMotivat0r** [comment]
@WazZro are you using express or justify?
P.S. You can make a request even without those options. Chill

**Comment by WazZro** [comment]
@zMotivat0r i'm using fastify
PSS i have tried to load relation without join in configuration and this doesnt work for me

**Comment by zMotivat0r** [comment]
@WazZro use this: https://github.com/fastify/fastify/blob/master/docs/Server.md#querystringparser

**Comment by zMotivat0r** [comment]
So, your issue is not actually 100% related to the crud lib but to the way how different express and fastify are parsing a query string params.

**Comment by zMotivat0r** [comment]
@WazZro all good now? let me know, please if it still doesn't work for you. Otherwise, we can close this, I suppose. Cheers!

**Comment by WazZro** [comment]
@zMotivat0r yes, it works! thanks :)
I think it’s worth adding to the documentation

**Comment by alphasen** [comment]
The link has moved to https://github.com/fastify/fastify/blob/77b75820be399d8d28bbda676c130ee2b90c3f52/docs/Reference/Server.md#querystringparser

```js
import fastify from 'fastify';
import qs from 'qs';

const fastifyInstance = fastify({
  querystringParser: (str) => qs.parse(str),
});

// balabala
// use instance
const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter(fastifyInstance));
```
