### ISSUE TITLE
Get returns always parent class fields when selecting a set of fields.

### ISSUE THREAD

**Issue by rahpuser** [nestjsx/crud#222]
Hello guys, I think this is a bug.

When having a Entity that extends BaseEntity, the get is always returning the BaseEntity fields, even if the query is `?fields=name%2Cprice`.

In this case, base entity has updatedAt and createdAt properties, and this 2 seems to always return.

Thanks

**Comment by Darkein** [comment]
I have a baseEntity with `createdAt` and `updatedAt` too, and I don't have any problem. Do you have the latest version ?

**Comment by rahpuser** [comment]
I see, thanks @Darkein going to try and update this thread.

**Comment by Darkein** [comment]
you're welcome, hope you fixed your problem !

**Comment by rahpuser** [comment]
Update:

You right,for some reason I just moved to latest and is working fine, closing this.
