### ISSUE TITLE
Dev dependencies installed as dependencies

### ISSUE THREAD

**Issue by alexmantaut** [nestjsx/crud#224]
Hi,

Thanks for the module, it is pretty useful!

I started using the module in my project, and noticed that my project started adding a lot more dependencies to my production package... In particular, it seems that typescript was added a dependency for production which bloated my package by 40 mb... If my understanding is correct, typescript should be added as a devDependency instead, as it is not necessary to use the compiled js code...

Also, there are some other packaging and testing dependencies that seem to have been added to dependencies...

I created a PR moving those dependencies to devDependencies... Please review it and let me know what you think.

Thanks,

**Comment by zMotivat0r** [comment]
It's a monorepo that hosts 4 npm packages, each of them has its own package.json.
So, root package.json is used for developing this project and not meant to be used in production.
