### ISSUE TITLE
[Feature Request/Discussion] Multi Tenancy / Row level Authorization

### ISSUE THREAD

**Issue by Bnaya** [nestjsx/crud#228]
I will soon need to implement some kind of Multi Tenancy / Row level Authorization (And even field level?) on top of nest/crud

And i would love to collect ideas to how to tackle it in the most integrated way.
If you did anything like that i would like to hear how you did it!

**Comment by ribegacul** [comment]
I did not implement access control with nestjsx/crud. But I have a couple of thoughts. See example:

```typescript
@Crud({
  model: { type: User }
})
@Controller("users")
export class UsersController {
  constructor(private readonly moduleRef: ModuleRef) {
  }

  @Override()
  getMany(
    @ParsedRequest() req: CrudRequest,
    @User() currentUser: User
  ) {
    const myCustomRepositoryWithAccessControl = new MyCustomRepositoryWithAccessControl(currentUser);
    const someOtherDependency = this.moduleRef.get(SomeOtherDependency);
    // Note: UsersService extends TypeOrmCrudService
    const usersService = new UsersService(myCustomRepositoryWithAccessControl, someOtherDependency);
    return usersService.getMany();
  }

}

```

**Comment by zMotivat0r** [comment]
@Bnaya does the new `@CrudAuth()` feature meet your request?

**Comment by Bnaya** [comment]
Is it documented yet?
I will try to play with it

**Comment by zMotivat0r** [comment]
@Bnaya new [`@CrudAuth()`](https://github.com/nestjsx/crud/wiki/Controllers#request-authentication) decorator is here

**Comment by Bnaya** [comment]
Looks very promising, didn't had time to try i yet
I'll close the issue and reopen if i will feel something is missing

Thanks!!
