### ISSUE TITLE
Filter join request to return only data of current user

### ISSUE THREAD

**Issue by MeMeMax** [nestjsx/crud#229]
Currently I got his in my Controller:

```
@Crud({
  model: {
    type: Broker
  },
  query: {
    join: {
      user: {
        eager: true,
        exclude: ['password']
      }
    }
  }
})
@Controller('broker')
@UseGuards(AuthGuard('jwt'))
export class BrokerController {
  constructor(public service: BrokerService) {}
}
```
There is a one to many relation between user and broker. I am authenticating the users by a jwt token and I need to filter the data on the id of the user. Is there any way to do this through the Crud configuration?

**Comment by MeMeMax** [comment]
Does no one use nestjsx/crud with authorization and user management or am I missing anything?

**Comment by NKJe** [comment]
Idk, but if i understand you correctly...
This solution might feel a bit hacky, but... maybe it'll be the right fit.
```
@Injectable()
export class SomeInterceptor implements NestInterceptor {
  intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
    const req = context.switchToHttp().getRequest();
    req.query.filter = 'userId||eq||' + req.user.id
    return next.handle();
  }
}
```
```
@Controller('broker')
@UseInterceptors(SomeInterceptor, CrudRequestInterceptor)
@UseGuards(AuthGuard('jwt'))
export class BrokerController {
  constructor(public service: BrokerService) {}
}
```
This works by adding to the query before the CrudRequestInterceptor.

**Comment by MeMeMax** [comment]
Thanks for your answer. This will only work for GET request I assume. But I have the same problem with Post requests. When a user adds a 'broker' the id of the current user should be inserted. In the last days thinking about this problem I came to the conclusion that nestjsx/crud is only for unauthenticated access or general ressources which are not security sensitive.

**Comment by NKJe** [comment]
You can make an interceptor do that to a `POST` too. I see your point though.

**Comment by chriszrc** [comment]
The interceptor is probably the way to go, but I overrode the getMany method for my initial solution, it does the same thing:

```
@Override()
  getMany(@ParsedRequest() req: CrudRequest, @PrincipalUser() user:PrincipalUser1) {
    //override the supplied user_id with the user_id of the logged in user (principal)
    req.parsed.filter.find(f=>f.field === 'user_id').value = user.user_id;
    return this.base.getManyBase(req);
  }
```

the @PrincipalUser annotation is just sugar for extracting the req.user:

```
export const PrincipalUser = createParamDecorator((data, req) => {
  return req.user as User1;
});
```

@loginov-rocks I think the way you're setting filter, you would override any existing filters that were supplied in the request? Probably not what most people want-

**Comment by zMotivat0r** [comment]
@chriszrc working on something similar that will be built in the lib

**Comment by chriszrc** [comment]
@zMotivat0r Great!! I'm kind of surprised that a security related lib/framework for nestjs hasn't already been developed, I related to @MeMeMax's question about people using nestjs with authorization, I struggled a bit too in the beginning to figure out the right ways to go-

**Comment by omerxx** [comment]
Any progress on this guys?
@zMotivat0r ?

**Comment by omerxx** [comment]
To whom this may concern, I implemented an "inteception-like" solution:
I'm overriding the relevant methods, adding `@Session` and using my cookie to filter the query.
It's much like the interceptor suggested by @NKJe and @loginov-rocks, but without actually creating it:

`x.controller.ts`:
```
  @Override()
  getMany(
    @ParsedRequest() req: CrudRequest,
    @Session() session,
  ) {
    req.options.query.filter = [
      {
        field: 'account.id',
        operator: 'eq',
        value: `${ session.accountId }`,
      },
    ];
    return this.base.getManyBase(req);
  }
```

**Comment by simonvizzini** [comment]
I'd also love to hear about progress on this. I'm very surprised this is not a built in feature yet. Is the majority of users really implementing unprotected CRUD APIs? I always assumed this is a basic requirement for any API that manages users. The workarounds suggested here are not satisfactory in my opinion, and I'd hate to have to roll my own CRUD APIs.

Other than that I really like nestjsx-crud, and I'd love to use it in a real project.

**Comment by ggirodda** [comment]
Same here, I really don't like to use a workaround to do something so evident in an API. I tried also to modify the `requst.options.query.filter` from the overridden controller function, to do the same thing, but it doesn't work as expected, the request options object seems to be always the same, and it isn't recreated for every request.
I really like the project too, other than that, thank you for your work.
