### ISSUE TITLE
Load eager relation data in GET request

### ISSUE THREAD

**Issue by dulkith** [nestjsx/crud#232]
```ts
@Crud({
  model: {
    type: Gate,
  },
})
@ApiUseTags('Gate')
@Controller('gate')
export class GateController {
  constructor(public service: GateService) {
  }
}
```

```ts
@Injectable()
export class GateService extends TypeOrmCrudService<Gate> {
  constructor(@InjectRepository(Gate) repo) {
    super(repo);
  }
}
```

```ts
@Entity()
export class Gate {
  @ApiModelProperty()
  @PrimaryGeneratedColumn()
  id: number;

  @ApiModelProperty()
  @Column()
  name: string;

  @ManyToOne(type => School, school => school.gates, {
    eager: true,
  })
  @JoinColumn({ name: 'school_id' })
  school: School;
}
```

**How to get out put as a eager.**

**Comment by bashleigh** [comment]
Yo! Thanks for the question! 
You can load eager relations like so 

```ts
@Crud({
  model: {
    type: Gate,
  },
  query: {
    joins: {
      school: {
        eager: true,
      },
    },
  },
})
```

**Comment by dulkith** [comment]
> ```ts
> @Crud({
>   model: {
>     type: Gate,
>   },
>   query: {
>     joins: {
>       school: {
>         eager: true,
>       },
>     },
>   },
> })
> ```

I got this error when I added this to the controller class
`error TS2322: Type '{ joins: { school: { eager: boolean; }; }; }' is not assignable to type 'QueryOptions'.
  Object literal may only specify known properties, but 'joins' does not exist in type 'QueryOptions'. Did you mean to write 'join'?
`

**Comment by Diluka** [comment]
typeorm is going to deprecate eager and lazy loading
see https://github.com/typeorm/typeorm/issues/3251
