### ISSUE TITLE
support mapping functionality

### ISSUE THREAD

**Issue by Diluka** [nestjsx/crud#24]
support `leftJoinAndMapOne` and `leftJoinAndMapMany`
http://typeorm.io/#/select-query-builder/joining-and-mapping-functionality

so we can flatten the results

**Comment by zMotivat0r** [comment]
So what about this? Do you want to implement it?

**Comment by Diluka** [comment]
No. Recently I have tried this function in `TypeORM`. It's strange.
Better using `orverride` to support this.
