### ISSUE TITLE
PATCH and PUT always create new record instead of updating

### ISSUE THREAD

**Issue by zaro** [nestjsx/crud#240]
Made a really simple CRUD for few models, following the tutorial but when using the  generated PUT and PATCH methods, new object is created every time, instead of being updated/replaced.

This is the model exposed via crud-typeorm:
```ts
@Entity("products" ,{schema:"public" } )
export class products {

    @PrimaryGeneratedColumn({
        type:"bigint", 
        name:"id"
        })
    id:string;
        

    @Column("text",{ 
        nullable:true,
        name:"name"
        })
    name:string | null;

   // Rest of fields omitted as not relevant
}
```

Basically I traced down the problem to the following :

Here is the updateOne method.

```js
    async updateOne(req, dto) {
        const found = await this.getOneOrFail(req);
        if (util_1.hasLength(req.parsed.paramsFilter) &&
            !req.options.routes.updateOneBase.allowParamsOverride) {
            for (const filter of req.parsed.paramsFilter) {
                dto[filter.field] = filter.value;
            }
        }
        return this.repo.save(Object.assign({}, found, dto));
    }
```

It correctly find the existing record, and then overrides the `id` field with the value in `req.parsed.paramsFilter`. And this is what breaks the update.

`repo.save` will compare the loaded entity to the one already in the database, but when loading it form the database `id` column will be string, and here the `id` coming from `req.parsed.paramsFilter` is Number making the comparison of ids always fail.

**Comment by zMotivat0r** [comment]
You need to add a `params` option in your CrudOptions ([docs](https://github.com/nestjsx/crud/wiki/Controllers#params)) and set `id` type to string. Because by default it's parsed a number.
```typescript
{
  params: {
    id: {
      field: 'id',
      type: 'string',
      primary: true,
    },
  },
}
```

**Comment by zaro** [comment]
@zMotivat0r thank you for the clarification. 

Added the configuration as per your suggestion, but it didn't help. When I set a breakpoint in `updateOne`, the req.parsed.paramsFilter[id] is still numeric one.

It seems that it is converted to number here :

```ts
  private paramParser(name: string): QueryFilter {
    validateParamOption(this._paramsOptions, name);
    const option = this._paramsOptions[name];
    const value = this.parseValue(this._params[name]);

    switch (option.type) {
      case 'number':
        validateNumeric(value, `param ${name}`);
        break;
      case 'uuid':
        validateUUID(value, name);
        break;
      default:
        break;
    }

    return { field: option.field, operator: 'eq', value };
  }
```
Maybe I am mistaken but I think there is something wrong with the logic here, as `parseValue` is called unconditionally,  and it looks like this:

```ts
    parseValue(val) {
        try {
            const parsed = JSON.parse(val);
            if (!util_1.isDate(parsed) && util_1.isObject(parsed)) {
                return val;
            }
            return parsed;
        }
        catch (ignored) {
            if (util_1.isDateString(val)) {
                return new Date(val);
            }
            return val;
        }
    }
```

So `const value = this.parseValue(this._params[name]);` when the param value is `"1"` will yield `1` because of JSON.parse.

I don't see how after `paramParser` the value in paramsFilter can possibly be string if it's valid number?

Any suggestions ?

**Comment by USA19** [comment]
This occurs due to the following reasons

TypeORM save() behavior (this is the core)

TypeORM rules:

Situation	Result
id exists and matches DB	UPDATE
id missing	INSERT
id exists but not found	INSERT
id wrong type	INSERT

Specifically, if we talk about the type it is talking about the type in here


@Crud({
  model: {
    type: WorkspaceService,
  },
  dto: {
    create: WorkspaceServiceCreate,
    update: WorkspaceService,
    replace: WorkspaceService,
  },
  params: {
    id: {
      field: 'id',
      type: 'string',   <<< here >>>
      primary: true,
    },
  },



After changing the string to a number, it seems to be working for me.
