### ISSUE TITLE
[crud-request] Incorrect "or" query parameter

### ISSUE THREAD

**Issue by hakimio** [nestjsx/crud#251]
I am building GET query parameters using `RequestQueryBuilder`:
```ts
RequestQueryBuilder
    .create(params)
    .query();
```
Where `params.or` is an array of `QueryFilter` objects. The generated query looks like the following:
```
or[]=address||cont||foo&or[]=city||cont||bar
```
which obviously is wrong and should be:
```
or=address||cont||foo&or=city||cont||bar
```

**Comment by zMotivat0r** [comment]
`or[]=address||cont||foo&or[]=city||cont||bar`
`or=address||cont||foo&or=city||cont||bar`

By saying `obviously` you mean that you think that `or[]` is incorrect param name and `or` is the correct one. Am I right?

**Comment by zMotivat0r** [comment]
@hakimio, please be advised to take a look at this issue https://github.com/nestjsx/crud/issues/216

**Comment by hakimio** [comment]
Yeah, maybe shouldn't have said _obviously_. 
Anyway, using `filter=firstName||cont||Hans&or=lastName||cont||Hans` works, but neither `filter=firstName||cont||Hans&or=lastName||cont||Hans&or=address||cont||foo&or=city||cont||bar` nor `filter=firstName||cont||Hans&or[]=lastName||cont||Hans&or[]=address||cont||foo&or[]=city||cont||bar` seem to be working as expected.

**Comment by hakimio** [comment]
@zMotivat0r Thanks, that was the issue.
