### ISSUE TITLE
[crud-request] Url encode pipe (|) character

### ISSUE THREAD

**Issue by hakimio** [nestjsx/crud#255]
AWS API Gateway throws 400 Client error whenever it finds pipe character (|) in url, it would be nice if `RequestQueryBuilder` could url encode those.

References:
[API Gateway Known Issues](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-known-issues.html#api-gateway-known-issues-rest-apis)
[StackOverflow](https://stackoverflow.com/a/50628533/3529279)

**Comment by zMotivat0r** [comment]
@hakimio, you can override filter param value delimiter in [Global Options](https://github.com/nestjsx/crud/wiki/Controllers#global-options) on you backend side setting `queryParser.delim` value to whatever fits your needs.
Also, if you're using `crud-request` package on your frontend, you can do the same as described [here](https://github.com/nestjsx/crud/wiki/Requests#customize).

**Comment by hakimio** [comment]
@zMotivat0r 
Thanks, looks like a good workaround for now. 
Still, I think, url encoding query parameters might be a good idea and shouldn't cause any issues.

**Comment by hakimio** [comment]
Fixed in the latest version of `crud-request` library.
