### ISSUE TITLE
Support: Relations

### ISSUE THREAD

**Issue by btd1337** [nestjsx/crud#264]
Hi devs,

Could anyone tell how I use relations with CRUD correctly?

**Expected behavior**

```
{
  "id": "x",
  "name": "x",
  "document": "x",
  "addressId": "x"
}
```

**Current http response**

addressId field is missing

![Captura de tela de 2019-09-18 12-30-46](https://user-images.githubusercontent.com/11943860/65163000-98d5ef80-da10-11e9-8fcf-8a9b5d7e85ee.png)

**My Classes**

`People - Entity`
![Captura de tela de 2019-09-18 12-28-33](https://user-images.githubusercontent.com/11943860/65162668-fc135200-da0f-11e9-9ede-40a3613ea333.png)

`Address - Entity`
![Captura de tela de 2019-09-18 12-28-48](https://user-images.githubusercontent.com/11943860/65162667-fb7abb80-da0f-11e9-822a-36d110aba80a.png)

`Customer - Controller`

> PS: Customer inherits from People

1) Code like in [Nest Documentation](https://docs.nestjs.com/recipes/crud)
![Captura de tela de 2019-09-18 12-24-20](https://user-images.githubusercontent.com/11943860/65162670-fc135200-da0f-11e9-85cf-ea87830ddcf4.png)
IDE reports an error

2) Code like in Nestjsx Crud Documentation
![Captura de tela de 2019-09-18 12-25-52](https://user-images.githubusercontent.com/11943860/65162669-fc135200-da0f-11e9-84bb-342d80ccf17b.png)

**Comment by Ttou** [comment]
same problem

**Comment by Darkein** [comment]
You want `adressId` or `address` ?
if you want `adressId`, take a look here: #111 

If you want  `address`, your configuration is correct, but you have to add it in the `join` queryParam in your url: [https://github.com/nestjsx/crud/wiki/Requests#join](https://github.com/nestjsx/crud/wiki/Requests#join) or add `eager: true` in your configuration to always get it: [https://github.com/nestjsx/crud/wiki/Controllers#join](https://github.com/nestjsx/crud/wiki/Controllers#join)

**Comment by zMotivat0r** [comment]
Looks like we need to fix a recipe in the Nest docs :(

**Comment by zMotivat0r** [comment]
@btd1337 @Ttou please let me know if you still have issues with enabling relations. Otherwise, please close this. Thanks!

**Comment by btd1337** [comment]
@Darkein @zMotivat0r The second tip: Getting the "address" object works, but what I need is just the "addressId" field.

Is it really necessary to create an "addressId" property in my entity class?

Is there no cleaner way to do this?

**Comment by zMotivat0r** [comment]
@btd1337 yes you neen to add `addressId` in your entity.

**Comment by Darkein** [comment]
And it's cleaner than getting a property not written in your model
