### ISSUE TITLE
Support Gateway just like Controller.

### ISSUE THREAD

**Issue by JeetChaudhari** [nestjsx/crud#27]
Please provide support for the gateways in same way controller works in this package with an option like enableControllers(default true), enableGateways(default false). 

For example, we would emit 'heroes' and it would return the array of heroes and 'heroes::heroId' would return hero with the specified id. 

This would allow accessing rest over WebSockets. If possible allow its usage with WsAdapter instead of socket.io for performance.

**Comment by zMotivat0r** [comment]
I'm not sure this will be done by me. If you have any ideas, please send a PR. Cheers!
