### ISSUE TITLE
empty OneToOne relationships do not return values

### ISSUE THREAD

**Issue by biammsilva** [nestjsx/crud#270]
I have a entity with at least 5 one to one relationships, when I use the get all endpoint, it returns nothing because it is making a inner join query, not a left join.

**Comment by zMotivat0r** [comment]
yeah, it's a known issue, will be fixed soon. Thanks.

**Comment by biammsilva** [comment]
> yeah, it's a known issue, will be fixed soon. Thanks.

There is a workaround to solve it for now?

**Comment by iamsteeve** [comment]
```tsx
// @ts-ignore left join only
// tslint:disable-next-line:only-arrow-functions
TypeOrmCrudService.prototype.getJoinType = function(s: string) {
    // tslint:disable-next-line:no-console
    return 'leftJoin';
};
```
This put it in your starting point is a quick and dirty solution in the future will give the option of obtaining the type of join.
