### ISSUE TITLE
Custom request query builder?

### ISSUE THREAD

**Issue by wxs77577** [nestjsx/crud#277]
We use raw  mongodb operators in json format for mongoose query, how could I use a custom request query builder?

Current:
`/api/users?page=1&limit=10&filter....`

What I need:
`/api/users?query={"page":1,"limit":10,"where":{"age":{$gte:18, $lte: 35}}}`

How could I achieve that?

**Comment by Diluka** [comment]
WIP #265

**Comment by zMotivat0r** [comment]
#265 merged. Docs will be added on release
