### ISSUE TITLE
ER_DUP_FIELDNAME: Duplicate column name

### ISSUE THREAD

**Issue by mreschke** [nestjsx/crud#281]
It is very common for databases to stick with underscore style column names, especially for relationships like user_id, category_id, space_id...

By default TypeORM names all relation columns in camelCase spaceId, userId....  You can override this behavior in TypeORM like so

```
@ManyToOne(type => Space, space => space.posts, { nullable: false })
@JoinColumn({ name: "space_id" }) // NOTICE I am telling TypeORM to use space_id
space: Space;
```

Now the database column is `space_id` instead of `spaceId`...good.  All works well across the board until CRUD does a JOIN.  I have only tested on a OneToMany.  My basic setup is a POSTS entity that can have ONE space.  So a basic OneToMany/ManyToOne relation is setup.  

When your JOIN query runs it actually runs 2 queries.  The first query errors with ER_DUP_FIELDNAME: Duplicate column name `space_id` because you assume you can call one of the columns as 'space_id' yourself, but its already taken.  Here is your first JOIN query that errors

```
SELECT
	DISTINCT `distinctAlias`.`Post_id` as ids_Post_id
FROM (
	SELECT
		`Post`.`id` AS `Post_id`,
		`Post`.`slug` AS `Post_slug`,
		`Post`.`title` AS `Post_title`,
		`Post`.`body` AS `Post_body`,
		`Post`.`hidden` AS `Post_hidden`,
		`Post`.`deleted` AS `Post_deleted`,
		`Post`.`indexed_at` AS `Post_indexed_at`,
		`Post`.`created_at` AS `Post_created_at`,
		`Post`.`updated_at` AS `Post_updated_at`,
------------------
PROBLEM IS HERE
		`space`.`id` AS `space_id`,
		`space`.`name` AS `space_name`,
		`space`.`section` AS `space_section`,
		`space`.`slug` AS `space_slug`,
		`space`.`order` AS `space_order`,
------------------
		`Post`.`parent_id`,
		`Post`.`space_id`,
		`Post`.`format_id`,
		`Post`.`created_by`,
		`Post`.`updated_by`
	FROM
		`posts` `Post`
		INNER JOIN `spaces` `space` ON `space`.`id`=`Post`.`space_id`
) `distinctAlias`
ORDER BY `Post_id` ASC LIMIT 25
```

Notice you are adding all your AS statements to the space table and assuming you can just append the column name after an _  as space_id, as space_name etc...well space_id is already used.  If you were to change your AS statement to something that couldn't possibly clash like space_table_id for example... or double understoce space__id, space__name etc...

Because of this I cannot set any of my ids to use underscores now.

**Comment by mreschke** [comment]
This is also related to #280.  Because if you fix #280 and eliminate that first query (which I think is pointless) you end up with only one actual JOIN query, and believe it or not that query does NOT complain if there are duplicate columns.  The second query that runs is this one

```
SELECT
	`Post`.`id` AS `Post_id`,
	`Post`.`slug` AS `Post_slug`,
	`Post`.`title` AS `Post_title`,
	`Post`.`body` AS `Post_body`,
	`Post`.`hidden` AS `Post_hidden`,
	`Post`.`deleted` AS `Post_deleted`,
	`Post`.`indexed_at` AS `Post_indexed_at`,
	`Post`.`created_at` AS `Post_created_at`,
	`Post`.`updated_at` AS `Post_updated_at`, 
	`space`.`id` AS `space_id`,
	`space`.`name` AS `space_name`,
	`space`.`section` AS `space_section`,
	`space`.`slug` AS `space_slug`,
	`space`.`order` AS `space_order`,
	`Post`.`parent_id`,
	`Post`.`space_id`,
	`Post`.`format_id`,
	`Post`.`created_by`,
	`Post`.`updated_by`
FROM
	`posts` `Post`
	INNER JOIN `spaces` `space` ON `space`.`id`=`Post`.`space_id`
```

Notice there are still 2 space_id columns in the result, by MySQL does not error.  Only in your first query that basically get a list of IDs only with a sub select query (distinctAlias) is the one that errors with duplicate issue.

**Comment by mreschke** [comment]
I have some new information on this.  If I comment out the `maxLimit: 25,` line in my controller the query changes to just a single proper JOIN without running 2 queries, the first of which crashes with the duplicate space_id column error.  Just like in #280, not sure why adding maxLimit would later one JOIN into 2 queries with an IN statement.  Either way, the first query still crashes with duplicate column.

**Comment by zMotivat0r** [comment]
@mreschke in the version `4.3.0-beta` the `alias` option for a relation was introduced. Please give it a shot and let me know if you still have an issue with this

**Comment by githubmann** [comment]
how to solve the problem

**Comment by zMotivat0r** [comment]
@githubmann as I mentioned in my last comment - use `alias`

**Comment by githubmann** [comment]
can you give some example code, thank you

**Comment by githubmann** [comment]
@zMotivat0r 
![image](https://user-images.githubusercontent.com/13065289/71308497-46093b00-2438-11ea-80de-362f132f125a.png)

i try, is ok. but no typo.

**Comment by zMotivat0r** [comment]
@mkelandis @githubmann is it still an issue when using with `alias`?

**Comment by githubmann** [comment]
@zMotivat0r that's no problem. just no type, must convert to 'any'. 
i appreciate your effort.

**Comment by kop7** [comment]
- "@nestjs/common": "^6.0.0"
- "@nestjsx/crud": "^4.4.0",
- "@nestjsx/crud-request": "^4.4.0",
- "@nestjsx/crud-typeorm": "^4.4.0",
- "typeorm": "^0.2.18"

#### the problem is still here?

```ts
@Entity('testA')
export class TestA {
    @PrimaryGeneratedColumn()
    id: number;
    
    @OneToOne(() => TestB, testb => testb.id, { cascade: true })
    @JoinColumn()
    test: TestB;
}
```

```ts
@Entity('testB')
export class TestB {
    @PrimaryGeneratedColumn()
    id: number;
    
    @OneToMany(() => TestC, testc => testc.cat, { cascade: true })
    testc: TestC[];

    @OneToMany(() => TestD, testd => testd.cat, { cascade: true })
    testd: TestD[];
}
```
```ts
@Crud({
    model: { type: TestA },
    query: {
        join:{
            'test': { eager: true},
            'test.testc': {alias: 'ttestc', eager: true} as any,
            'test.testd': {alias: 'ttestd',  eager: true} as any,
        }
    }
})
```

` GET api/tests/1`


error: "message": "ER_DUP_FIELDNAME: Duplicate column name 'catId'",

**Comment by zMotivat0r** [comment]
@kop7 set an alias for `test` relation too

**Comment by satuuntuksemuaaja** [comment]
alias not work for me

**Comment by strelov1** [comment]
I have the same problem, alias no work for me too

**Comment by valdeua** [comment]
@michaelyali  Looks like the same problem in my case  Alias doesn't work in my case.    
[Nest] 39063  - 11/30/2022, 12:11:42 PM   ERROR [ExceptionsHandler] Duplicate column name 'Fundraising_id'

```js
@Crud({
  model: {
    type: Fundraising,
  },
  query: {
    join: {
      fundraiser: {
        eager: false,
        alias: 'fr',
      },
      cards: {
        eager: false,
        alias: 'c',
      },
    },
  },

``` 
Models:

```js
export abstract class BaseEntity {
    @PrimaryGeneratedColumn()
    id: number;

    @CreateDateColumn()
    createdAt: Date;

    @UpdateDateColumn()
    updatedAt: Date;

    @DeleteDateColumn()
    deletedAt: Date;
}
```

```js
@Entity()
export class Fundraising extends BaseEntity {
    @Column()
    @Index({ unique: false })
    name: string;

    @ManyToOne(() => Fundraiser, (f) => f.fundraisingList, {
        nullable: true,
        eager: true,
    })
    @JoinColumn()
    fundraiser: Fundraiser;
}
```


```js
@Entity()
export class Fundraiser extends BaseEntity {
    @Column()
    @Index({ unique: false })
    name: string;

    @Column()
    photo: string;

    @OneToMany(() => Fundraising, (fr) => fr.fundraiser, {
        nullable: true,
    })
    fundraisingList: Fundraising[];
}

```



Also, I want to highlight 'It appears after I pass ?limit= ' as it vas in @mreschke case https://github.com/nestjsx/crud/issues/281#issuecomment-536110620

When I requested API with a limit I have 500 
![image](https://user-images.githubusercontent.com/7124478/204772880-3e4ab527-1acb-44cc-beda-017c2f03d883.png)

And error 
![image](https://user-images.githubusercontent.com/7124478/204773004-f863324a-3664-439c-896d-b5f1f58b2f46.png)

Without limit it's 200 
![image](https://user-images.githubusercontent.com/7124478/204773218-b0947afb-8371-41b3-9731-55fb832fc721.png)

Generated query is:
```mysql
SELECT DISTINCT `distinctAlias`.`Fundraising_id` AS `ids_Fundraising_id`, `distinctAlias`.`Fundraising_id`
FROM (SELECT `Fundraising`.`id`                AS `Fundraising_id`,
             `Fundraising`.`id`                AS `Fundraising_id`,
             `Fundraising`.`createdAt`         AS `Fundraising_createdAt`,
             `Fundraising`.`updatedAt`         AS `Fundraising_updatedAt`,
             `Fundraising`.`deletedAt`         AS `Fundraising_deletedAt`,
             `Fundraising`.`isPublished`       AS `Fundraising_isPublished`,
             `Fundraising`.`name`              AS `Fundraising_name`,
             `Fundraising`.`description`       AS `Fundraising_description`,
             `Fundraising`.`target`            AS `Fundraising_target`,
             `Fundraising`.`monoJarUrl`        AS `Fundraising_monoJarUrl`,
             `Fundraising`.`raisedMono`        AS `Fundraising_raisedMono`,
             `Fundraising`.`raisedExternally`  AS `Fundraising_raisedExternally`,
             `Fundraising`.`image`             AS `Fundraising_image`,
             `Fundraising`.`isEnded`           AS `Fundraising_isEnded`,
             `Fundraising`.`reportVideoLink`   AS `Fundraising_reportVideoLink`,
             `Fundraising`.`reportPhoto`       AS `Fundraising_reportPhoto`,
             `Fundraising`.`reportDescription` AS `Fundraising_reportDescription`,
             `fr`.`id`                         AS `fr_id`,
             `fr`.`id`                         AS `fr_id`,
             `fr`.`createdAt`                  AS `fr_createdAt`,
             `fr`.`updatedAt`                  AS `fr_updatedAt`,
             `fr`.`deletedAt`                  AS `fr_deletedAt`,
             `fr`.`name`                       AS `fr_name`,
             `fr`.`description`                AS `fr_description`,
             `fr`.`photo`                      AS `fr_photo`,
             `Fundraising`.`fundraiserId`
      FROM `fundraising` `Fundraising`
               LEFT JOIN `fundraiser` `fr` ON `fr`.`id` = `Fundraising`.`fundraiserId` AND (`fr`.`deletedAt` IS NULL)
      WHERE `Fundraising`.`deletedAt` IS NULL) `distinctAlias`
ORDER BY `distinctAlias`.`Fundraising_id` DESC, `Fundraising_id` ASC LIMIT 100
```
