### ISSUE TITLE
How to use a `createOne` function not from a controller?

### ISSUE THREAD

**Issue by omerxx** [nestjsx/crud#284]
Hi!

After building my controller and service based on CRUD, I'd like to create an object in the DB from my own code using the service and not through the API controller.
Is this possible?

The method asks for a `req: CrudRequest, dto: T` which I'm not sure how to provide. 
Pretty sure the `dto` is the object that should be created but I can't figure out the `CrudRequest`. Any help / example?

**Comment by zMotivat0r** [comment]
Hi @omerxx 
Thanks for your question. But I would like to suggest you read the wiki first.
There is a [chapter](https://github.com/nestjsx/crud/wiki/Controllers#adding-routes) describing how to add a new controller route and use `CrudRequest` object by applying `CrudRequestInterceptor`.
Please bear in mind that CrudService was designed to be used in the CrudController and that's totally lakes sense because the lib is all about creating crud controllers and services. That's why it requires a `CrudRequest` object.

**Comment by omerxx** [comment]
@zMotivat0r I've actually read it multiple times, it still doesn't answer my question:
I don't need another controller route, I want to use the existing `createOne` under the CRUD `service` from my own code just like I'd use TypeORM with `.create`.
But I don't know how to provide `CrudRequest` when this is not an actual HTTP request, my own own code calling the service method.

Could you please advise?

**Comment by zMotivat0r** [comment]
@omerxx as I said previously, the CrudService was designed to be used in the CrudController. We pass CrudRequest because there is a need to pass parsed params, parsed query, controllers (even routes options), etc.
Anyway, you can always override or extend the CrudService to fit your needs.

**Comment by justheath** [comment]
I think this is the same question I have and I'm not sure of the correct way to handle the `CrudRequest`.

For example: 
  The default controller calls my override for `createOne` and gives me a `req: CrudRequest`. 
But before I call `super.createOne(req, dto)`, I need to call _another_ injected service to create some dependencies. 

Do I just pass the original `req` to my other service too? Or can / should I create a new request specific to that service / entity?

**Comment by tanlanchou** [comment]
like this? 

```
export abstract class CommonService<T> extends TypeOrmCrudService<T> {
    constructor(repo: Repository<T>) {
        super(repo);
    }

    async create(dto: DeepPartial<T>): Promise<T> {
        return this.repo.save(dto);
    }

   ...
```
