### ISSUE TITLE
Global options have no effect

### ISSUE THREAD

**Issue by omerxx** [nestjsx/crud#288]
I've tested every possible option but this from my `main.ts`:
```typescript
import { CrudConfigService } from '@nestjsx/crud';

CrudConfigService.load({
  routes: {
    exclude: ['createManyBase'],
  },
});

```

Routes still exist in all modules.

**Comment by zMotivat0r** [comment]
is it **Nrwl NX**?

**Comment by omerxx** [comment]
@zMotivat0r Thanks for the quick reply!
No, it isn't

**Comment by zMotivat0r** [comment]
@omerxx it's working, I think you just don't use it right or read wiki not carefully enough.
Please see https://github.com/nestjsx/crud/commit/2a6465f353da6f24d16f2e55aa281fb73a354f45
