### ISSUE TITLE
GetManyDefaultResponse<T> is not iterable

### ISSUE THREAD

**Issue by omerxx** [nestjsx/crud#290]
I'm trying to `Override()` my `getMany` controller in order to change one of the fields of the object before it's returned to the user.
On `getOne` I had no problem, but the object that returns from `getMany` is not iterable:
```typescript
  @Override()
  getMany(@ParsedRequest() req: CrudRequest) {
    const stacks = this.base.getManyBase(req);
    for (const stack of stacks) {
      stack.status = 'newstatus';
    }
    return stacks;
  }
```
Yields this error:
```
Type 'GetManyDefaultResponse<Stack>' must have a '[Symbol.iterator]()' method that returns an iterator.
```

Am I missing something?

**Comment by zMotivat0r** [comment]
It returns eather an array or a pagination object. It depends on what query params do you pass.
Also, one suggestion - you can use interceptor to customize the response without a need to override a method.

**Comment by omerxx** [comment]
@zMotivat0r Thanks again for your quick responses and communication this is awesome :)

About the object returned - my code is exactly as above, the thing is - I'm being stopped by the compiler before it's even running because the compiler won't let me iterate over an object it is uncertain about. I had to copy my `Stack` object into a new one of type `any` to be able to just run an iteration.

About interception - I actually am using one for the authorization (as suggested on https://github.com/nestjsx/crud/issues/229), but for this one, I think the better approach for a more readable code is actually under the controller.

**Comment by zMotivat0r** [comment]
>I'm being stopped by the compiler before it's even running because the compiler won't let me iterate over an object it is uncertain about. I had to copy my Stack object into a new one of type any to be able to just run an iteration.

So it's not about a lib itself, because as I've mentioned it returns either an array or an object
