### ISSUE TITLE
POST

### ISSUE THREAD

**Issue by NaturesProphet** [nestjsx/crud#3]
Hello,
nice job dude!

i have a problem with the POST route. 
i'm trying to send a json to the POST endpoint using the Postman app, the json looks like this:
{
	"login": "nature",
	"senha": "123",
	"nome": "Nature"
}

but i receive a 400 error saying this:
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "null value in column \"login\" violates not-null constraint"
}

it looks like the json that i'm trying to send is not being understood by the app server. 
Can you help ?

PS: the other endpoints (GET) are working pretty well

**Comment by zMotivat0r** [comment]
@NaturesProphet there is a major update, please try the new version, please. Closing this for now.
