### ISSUE TITLE
Need real_escape_string before SQL search

### ISSUE THREAD

**Issue by zxf4399** [nestjsx/crud#311]
Hey,
I found a bug when handle request.When i want to search data and provider filter field like
?filter=name||cont||zxf4399 
OK I will find the data about it
but when i change filed like
?filter=name||cont||zxf4399%
ite can also world 
that's impossible!
i find this is real_escape_string
can you help me how to solve it

**Comment by Darkein** [comment]
it's because `%` is a protected word in mysql. Try to backslash it : `?filter=name||cont||zxf4399\%`

**Comment by zMotivat0r** [comment]
also, with version `4.3.0` a new `search` query param was introduced. It's already present in `@nestjsx/crud-request` and the docs will be added soon.
In addition, the old `filter` and `or` query params will likely be deprecated and removed in v5.0.0, and starting from now I won't be supporting those query params and suggest everyone use new `search`  feature
