### ISSUE TITLE
Query Builder is not supported by MongoDB

### ISSUE THREAD

**Issue by GregHub47** [nestjsx/crud#312]
Hi,

I'm trying to make a restfulapi with MongoDB & CRUD & TypeORM.

POST method is OK, but GET give an error :
Query Builder is not supported by MongoDB

It seems the MongoDB repo of TypeORM doesn't support createQueryBuilder.

Is there something i've missed ? How can i make it work ?

Thank for your help,

**Comment by ruscon** [comment]
ping

**Comment by GregHub47** [comment]
Sorry for the duplicate, i've made a search, but not seen that default search is only on opened ticket.
thank you for your help :)
