### ISSUE TITLE
Handle TypeOrm Tree Entities

### ISSUE THREAD

**Issue by mucan** [nestjsx/crud#315]
First of all thanks to all of you for this awesome library! 

My question is about how to handle tree entities from TypeORM. Up to now I am writing customized controllers to get parents and descendants, but is there a simpler or faster way which you have already implemented and I didn't found?

**Comment by zMotivat0r** [comment]
Hi,
tree repositories are not supported by this lib

**Comment by mucan** [comment]
OK! Thank you.

**Comment by mucan** [comment]
OK! Thank you.

**Comment by mubasshir** [comment]
any workaround to support this?
