### ISSUE TITLE
Just use service

### ISSUE THREAD

**Issue by zerox12311** [nestjsx/crud#316]
Hi, I want to use this library just server part.
How can I do?
Can support just service library and property interface?

**Comment by zMotivat0r** [comment]
So you can just use the service. Do you have any particular questions about it? https://github.com/nestjsx/crud/wiki/ServiceTypeorm - that's how you use crud service

**Comment by zerox12311** [comment]
I know. But when I use service, I don't know what parameter should I send.
The **CrudRequestOptions** is too complex to understand.
Or any method can help me to create **CrudRequestOptions**??

**Comment by zerox12311** [comment]
Have any news?

**Comment by zMotivat0r** [comment]
with v `4.3.0-beta.2` (or any other 4.3.0-beta) you can use `CrudRequestInterceptor` in any controller or a method, not just in the crud controller or a method. Here is an [example](https://github.com/nestjsx/crud/wiki/Controllers#adding-routes)
