### ISSUE TITLE
Use Sequelize instead

### ISSUE THREAD

**Issue by SamiSammour** [nestjsx/crud#32]
Hello there,
You have made a great work in this so I was wondering if there's any way I can use sequelize instead of typeorm? and if so can you tell how and where to change? I've used sequelize many times and I'm aware of mostly all of its features and I'm not ready to try another ORM..

**Comment by zMotivat0r** [comment]
Hey. I'm not sure I'll have time in the nearest future to do this. Also, we have faced some problems with Sequelize when we were working with almost 2 years ago with the first versions of NestJs. Maybe, the situation has changed. Anyways, I'd like to see your PR if any interest. Cheers!

**Comment by SamiSammour** [comment]
I'll be working on it in the following days. Thanks anyway.

**Comment by killerall** [comment]
@SamiSammour Hello, is there any news about this? I can try to implement, but I would like to know if it is already being developed.

**Comment by SamiSammour** [comment]
Hi @killerall actually I couldn't make any progress with it due to an issue between sequelize and class-transformer which nestjs itself heavily rely on it.
Here's the issue without any update on it: https://github.com/typestack/class-transformer/issues/242

**Comment by SamiSammour** [comment]
Hello @killerall. is there any progress on this? I think I'm back on this but looks like some APIs have changed from `sequelize` & `sequelize-typescript` and it might take some time with me.. so I was wondering if you have made anything about this?
