### ISSUE TITLE
Strange 'factory' variable assignment

### ISSUE THREAD

**Issue by mikeconley12** [nestjsx/crud#329]
I have a small question. Why do you need this line of code `factory = undefined;` https://github.com/nestjsx/crud/blob/master/packages/crud/src/decorators/crud.decorator.ts#L6 ?

```typescript
import { CrudRoutesFactory } from '../crud';
import { CrudOptions } from '../interfaces';

export const Crud = (options: CrudOptions) => (target: Object) => {
  let factory = CrudRoutesFactory.create(target, options);
  factory = undefined;
};
```

I am going to make some patches to your package, can you please clarify this moment?

**Comment by zMotivat0r** [comment]
@mikeconley12 I just wanted to make sure that in case of closure `factory` won't hang in memory. That's it

**Comment by mikeconley12** [comment]
@zMotivat0r Thanks for your reply! This is an interesting case :)
But I do not see any memory issues. We use the `factory` variable only inside the `Crud` function.

**Comment by Darkein** [comment]
actually `factory` is not used, you could just remove it :)
