### ISSUE TITLE
Mock RepositoryService Test

### ISSUE THREAD

**Issue by mathieugeissler** [nestjsx/crud#33]
Hello,

Is it possible to mock my services with RepositoryService extended ?
Exemple I have a service and I want to test my customMethod

user.service.ts
```typescript
@Injectable()
export class UsersService extends RepositoryService<User> {
  constructor(
    @InjectRepository(User)
    private readonly usersRepository: Repository<User>,
  ) {
    super(usersRepository);
  }

  public findByCognitoId(cognitoId: string): Observable<User> {
    return from(
      this.usersRepository.findOneOrFail({ cognitoId: cognitoId }),
    );
  }
  
  public customMethod() {
    return null;
  }
}
```
user.service.spec.ts:
```typescript
describe('UsersService', () => {
  let service: UsersService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        UsersService,
        { provide: getRepositoryToken(User), useClass: Repository },
      ],
    }).compile();
    service = module.get<UsersService>(UsersService);
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });
});
```

But I get an error : `TypeError: Cannot read property 'columns' of undefined`

thanks

**Comment by fwoelffel** [comment]
Same issue here.
This is where the exception is thrown: https://github.com/nestjsx/crud/blob/master/src/typeorm/repository-service.class.ts#L31

**Comment by fwoelffel** [comment]
@zMotivat0r could you provide any instructions on how to test a `RepositoryService`?
Also, I'm wondering if the `RepositoryService.{entityColumnsHash,entityRelationsHash}` abstraction layer is really needed?

**Comment by fwoelffel** [comment]
Here is what I came up with:

```js
import { Test, TestingModule } from '@nestjs/testing';
import { getRepositoryToken } from '@nestjs/typeorm';
import { AnnotationsService } from './annotations.service';
import { AnnotationEntity } from '../entities/annotation.entity';

describe('AnnotationsService', () => {
  let service: AnnotationsService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        AnnotationsService,
        {
          provide: getRepositoryToken(AnnotationEntity),
          useValue: {
            metadata: {
              columns: [],
              relations: [],
            }
          }
        }
      ],
    }).compile();

    service = module.get<AnnotationsService>(AnnotationsService);
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });
});
```
This is far from perfect and I can't imagine keeping this kind of mock if I want to perform more complex tests. I think it is worth the pain to also ask this question to the TypeORM guys.

**Comment by zMotivat0r** [comment]
So basically it's the same as you would mock TypeORM Repository in your project without using crud lib. I don't think that mocking it should be a part of this lib.

**Comment by fwoelffel** [comment]
Yes, I also think this issue is more related to TypeORM than to this library.

**Comment by fwoelffel** [comment]
There are apparently two main way of doing things. See https://stackoverflow.com/questions/52797727/process-of-testing-with-typeorm-and-nestjs-and-jest-using-mocks for a good introduction.

**Comment by mathieugeissler** [comment]
thanks it's works now with metadata field :)
