### ISSUE TITLE
How to authorize all rotes in the same time of one controller.

### ISSUE THREAD

**Issue by dcyrillo** [nestjsx/crud#337]
I'm using the lib to authorize methods , i would like to know how to authorize them .

**Comment by zMotivat0r** [comment]
https://github.com/nestjsx/crud/blob/8ef174f5ebf4e798d571a93d9d01cfb04f5bcbe9/integration/crud-typeorm/projects/my-projects.controller.ts#L28-L35
`@CrudAuth` added in version 4.3.0-alpha.0
The documentation will be added soon
