### ISSUE TITLE
Property 'intercept' in type 'CrudRequestInterceptor' is not assignable to the same property in base type 'NestInterceptor<any, any>'.

### ISSUE THREAD

**Issue by shushlyakov** [nestjsx/crud#341]
"@nestjs/common": "^6.10.8",
    "@nestjs/core": "^6.10.8",
    "@nestjsx/crud": "^4.2.0",
    "@nestjs/platform-express": "^6.10.8",
    "@nestjs/swagger": "^4.0.9",
    "@nestjs/typeorm": "^6.2.0",

Error:
../node_modules/@nestjsx/crud/lib/interceptors/crud-request.interceptor.d.ts:3:5 - error TS2416: Property 'intercept' in type 'CrudRequestInterceptor' is not assignable to the same property in base type 'NestInterceptor<any, any>'.

Type '(context: ExecutionContext, next: CallHandler<any>) => Observable<any>' is not assignable to type '(context: ExecutionContext, next: CallHandler<any>) => Observable<any> | Promise<Observable<any>>'.

Type 'Observable<any>' is not assignable to type 'Observable<any> | Promise<Observable<any>>'.

**Comment by zMotivat0r** [comment]
fixed in `4.3.0-beta.1`
