### ISSUE TITLE
Custom Error Handling

### ISSUE THREAD

**Issue by iamclaytonray** [nestjsx/crud#352]
Currently, if there's an error, all the server throws is a `500 / Internal Server Error`, which is not very helpful. This is a feature request to enable custom error handling unless it already exists. If it does exist, can you point me to an example?

**Comment by zMotivat0r** [comment]
Have you tried using https://docs.nestjs.com/exception-filters ?

**Comment by iamclaytonray** [comment]
Would I inject that? My goal is for CRUD to find the most relevant error and throw that instead of the default error that's thrown.

**Comment by zMotivat0r** [comment]
First, I have no idea what default error are you talking about. It's would be great if you could provide more details, some logs or a screenshot.
Second, as I mentioned previously - have you used exception filters in your project? Have you used them before maybe? I'm just trying to understand and help you :)
Thanks

**Comment by iamclaytonray** [comment]
I was missing some knowledge on how this framework works. Specifically, I was missing the following:

```ts
params: {
    id: {
      field: 'id',
      type: 'uuid',
      primary: true,
    },
  },
```
