### ISSUE TITLE
getPrimaryParam

### ISSUE THREAD

**Issue by njournaud** [nestjsx/crud#359]
Hello guys! 
Thank you for the new release!
I have a question about how using getPrimaryParam on createOneBase.
My entity PK is 'code' and not 'id'
When I'm Posting a select distinc with 'entity'.id failed because I don't have id on this entity so I'm thinking that I need to make 'code' the primaryParam ?

Thank you again! Great job!

Nico

**Comment by zMotivat0r** [comment]
https://github.com/nestjsx/crud/wiki/Controllers#params
there is a `field` property to set your primary param name

**Comment by njournaud** [comment]
I already set this into my controller : 
 params: {
    id: {
      field: 'code',
      type: 'string',
      primary: true,
    },
  },

**Comment by zMotivat0r** [comment]
yeah @njournaud I see the issue, will fix it

**Comment by njournaud** [comment]
Thank just for precision when i put 
`createOneBase: {
      returnShallow: true,
    },`
that work ;)
