### ISSUE TITLE
Relation data not available

### ISSUE THREAD

**Issue by rajkumarpb** [nestjsx/crud#360]
Models:
```

import {Column,Entity, OneToMany,PrimaryGeneratedColumn} from "typeorm";
import { WLogin } from "./wlogin.entity";

@Entity("users" ,{schema:"public" } )
export class Users {

    @PrimaryGeneratedColumn({
        type:"bigint", 
        name:"id"
        })
    id:string;
        
    @Column("name")
    name:string | null;       

    @OneToMany(()=>WebLogin, (wlogin: WLogin)=>wlogin.user,{ onDelete: 'CASCADE' ,onUpdate: 'CASCADE' })
    wLogins:WLogin[]; 
}
```

WLogin

```
import { Column,Entity,Index,JoinColumn,ManyToOne,PrimaryGeneratedColumn, JoinTable } from "typeorm";
import { Users } from "./users.entity";

@Entity("wlogin" ,{schema:"public" })
export class WebLogin {

    @PrimaryGeneratedColumn({
        type:"bigint", 
        name:"id"
        })
    id:string;
        
    @JoinColumn({ name:'user_id'})
    @ManyToOne(type => Users, users => users.id)
    user:Users | null;
        
}
```

But when I hit the service http://localhost:3000/weblogin?join=users, I'm only getting fields from wlogin table. But it should display the users name as well as mentioned in the entity. Can someone tell me what am I doing wrong in this case?

**Comment by zMotivat0r** [comment]
@rajkumarpb yeah, I can tell you for sure. Please read the docs.
https://github.com/nestjsx/crud/wiki/Controllers#join

>An Object of relations that allowed to be fetched by passing join query parameter in GET requests.
Each key of join object must strongly match the name of the corresponding resource relation. If particular relation name is not present in this option, then user will not be able to get this relational objects in GET request.

**Comment by rajkumarpb** [comment]
So I need to change the column id in Users table as 'user_id'? Is it what it implies?

**Comment by zMotivat0r** [comment]
@rajkumarpb no, you need to list allowed relations in you controller
show me your controller please?

**Comment by rajkumarpb** [comment]
Controller:

```
import { Controller } from '@nestjs/common';
import { Crud, CrudController } from '@nestjsx/crud';
import { WebLogin } from '../model/wlogin.entity';
import { WebLoginService } from '../service/wlogin.service';

@Controller('weblogin')
@Crud({
  model: {
      type: WebLogin,
  },
  query: {
      join: {
          users: {
              eager: true,
              allow:['name']
          }
      }
  }
})
export class WebLoginController implements CrudController<WebLogin> {
  constructor(public service: WebLoginService) {}
}
```

**Comment by zMotivat0r** [comment]
>@ManyToOne(type => Users, users => users.id)
    user:Users | null;

>join: {
          users: {
              eager: true,
              allow:['name']
          }
      }

your relation in the entity is `user` but in the controller, you specify `users`
As I said earlier, please read the docs

**Comment by rajkumarpb** [comment]
That's it! That's the issue. Too embarrassing to have such silly mistake. Thanks @zMotivat0r

**Comment by rajkumarpb** [comment]
That's it! That's the issue. Too embarassing to have such silly mistake. Thanks
