### ISSUE TITLE
Docs have incorrect query operators

### ISSUE THREAD

**Issue by pizzafox** [nestjsx/crud#372]
The [documentation](https://github.com/nestjsx/crud/wiki/Requests#query-params) still lists operators like `$eq` and `$notnull` but that is no longer accurate. Instead of `$eq` it should be `eq`, `$notnull` -> `notnull`, etc.

~~Using the outdated operators will cause a 5XX error from the server:~~
Edit: This was because I was using an outdated version of the module.
```
Invalid comparison operator. eq,ne,gt,lt,gte,lte,starts,ends,cont,excl,in,notin,isnull,notnull,between expected
```

**Comment by zMotivat0r** [comment]
fixed with `4.3.3` (https://github.com/nestjsx/crud/issues/370)
