### ISSUE TITLE
basic setup isn't working as documented 

### ISSUE THREAD

**Issue by tawfekov** [nestjsx/crud#378]
Hello , 
I'm trying to test out `nestjsx/crud` with blank nestjs project , I followed up the [docs](https://docs.nestjs.com/recipes/crud-utilities) page but I'm getting this error blow 

`[Nest] 4704   - 01/01/2020, 6:45:48 PM   [ExceptionHandler] Class constructor TypeOrmCrudService cannot be invoked without 'new' +2ms
TypeError: Class constructor TypeOrmCrudService cannot be invoked without 'new'
    at new CatalogService (build/catalog/catalog.service.js:35:23)
    at Injector.instantiateClass (node_modules/@nestjs/core/injector/injector.js:288:19)
    at callback (node_modules/@nestjs/core/injector/injector.js:75:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

I've tested it on the following nest cli versions : 
- 6.11.5
- 6.12.9 

My node version : v10.16.0 

how can get it up and running ?

**Comment by zMotivat0r** [comment]
It indeed works. Please take a look at the [exmaple](https://github.com/nestjsx/crud/tree/master/integration/crud-typeorm).

**Comment by tawfekov** [comment]
okay @zMotivat0r  , I'll delete everything and start over , I'll re open this case if issue persisted 

thanks @zMotivat0r

**Comment by codepushr** [comment]
For anyone stumbling over this issue: it's probably a tsconfig issue. Try bumping your `target` from `es5` to `es6`.
