### ISSUE TITLE
[Question] Nested search query

### ISSUE THREAD

**Issue by hakimio** [nestjsx/crud#380]
What's the best way to write nested search queries using `s` query parameter? I would like to translate following SQL search into JSON search condition:
```sql
`field` = 10 AND (`otherField` < 3 OR `otherField` > 11)
```

**Comment by zMotivat0r** [comment]
```typescript
{
  $and: [
    {
      field: 10
    },
    {
      otherField: {
        $or: {
          $lt: 3,
          $gt: 11
        }
      }
    }
  ]
}
```

**Comment by hakimio** [comment]
@zMotivat0r Maybe this kind of example could also be added to the wiki? 
Also, is the following conversion correct:
SQL:
```sql
`field1` = 10 AND (`field2` < 3 OR `field3` > 11)
```
JSON search condition:
```js
{
  $and: [{
    field1: 10
  }, {
    $or: [{
      field2: {
        $lt: 3
      }
    },
    {
      field3: {
        $gt: 11
      }
    }]
  }]
}
```

**Comment by zMotivat0r** [comment]
yep, as I wrote in the wiki, there is a LOT of variations, like, I think every possible? :)
