### ISSUE TITLE
How do I apply multiple joins?

### ISSUE THREAD

**Issue by xianghu1314** [nestjsx/crud#381]
I see the example: GET /heroes/25?join=profile||address,bio
How do I apply multiple joins?
i try to do this: GET /heroes/25?join=profile|profile2 , but it dosent work.
then i try to do this: GET /heroes/25?join=profile&join=profile2 , it work well.
but I shared this parameter with my front-end colleagues and he had a hard time with it,
if this way is not suitable for this http method?
Thanks for your reply @jdguzman @frco9 @avatsaev @asheliahut @NKJe

**Comment by zMotivat0r** [comment]
I wonder why you've opened an issue if your question already contains an answer?
Please read the [docs](https://github.com/nestjsx/crud/wiki/Requests#join)
Also, I wonder what kind of "hard times" do your colleagues have? I thought it's pretty straight forward to create a query string.
Anyways, if your colleagues work on the front-end side (assume they create a web app), they could use [query builder](https://github.com/nestjsx/crud/wiki/Requests#frontend-usage)

**Comment by avatsaev** [comment]
It's suitable and it's in the docs
