### ISSUE TITLE
Querying Relational Data

### ISSUE THREAD

**Issue by iamclaytonray** [nestjsx/crud#383]
In the link below, sub-endpoints are generated for relational data. I've tried a bunch of things today and so far, I haven't been able to generate a sub-route / sub-endpoint. I did start with the example and that wasn't too helpful for me either. I'll try to push a repro within the next hour or so.

https://github.com/nestjsx/crud/wiki/Controllers#api-endpoints

**Comment by zMotivat0r** [comment]
Hi,
I'm a little bit confused when you say `sub-endpoints are generated for relational data`
They are not generated automatically by any means if I get you right.
[Params](https://github.com/nestjsx/crud/wiki/Controllers#params) wiki section has an example of enabling params validation and persisting those params in a request body. That's it. The lib doesn't generate any sub-endpoints.
Here is an example:
https://github.com/nestjsx/crud/blob/ded1845ffd92d3dda9bbb49248b334a2b5ea7ff0/integration/crud-typeorm/users/users.controller.ts#L18-L28
Here, on create/update actions `companyId` will be taken from the URL params and will be ignored if it was in the body, at least unless you set `allowParamsOverride` to `true` ([routes options](https://github.com/nestjsx/crud/wiki/Controllers#routes))

**Comment by iamclaytonray** [comment]
The section of the docs says that using the Crud decorator will generate endpoints such as these: `GET /heroes/:heroId/perks`

Am I missing something?

**Comment by zMotivat0r** [comment]
Yeah, it generates 7 endpoints just for the entity that one provides in the `@Crud` decorator options.
Also, as you can see, the lib doesn't even care about what relations an entity might have unless [join options](https://github.com/nestjsx/crud/wiki/Controllers#join) are set. `/heroes/:heroId/perks` just means that the lib can handle URL params too and the mechanism is described in the wiki and in my previous message. 
Sorry, but as I said it doesn't generate any sub-endpoints. Although this may seem like a good idea at first glance, then it becomes obvious that maintenance of this will be terrible.
