### ISSUE TITLE
How to get service from persist and filter functions?

### ISSUE THREAD

**Issue by MatisiekPL** [nestjsx/crud#388]
Hello,
How can I get service from dependency injection container inside `persist` or `filter` function in `@CrudAuth`? 👏 I need to query some data there. 👍 What should I do? If it is not implemented yet 😨, please provide temporary workaround. 😎
Thanks,
Matt from Poland

**Comment by zMotivat0r** [comment]
It's not implemented and I believe it won't be implemented because those are simple functions.
If you need  services or other NestJs DI stuff you should consider using interceptors
