### ISSUE TITLE
create row with relation (doc)

### ISSUE THREAD

**Issue by bardak-dev** [nestjsx/crud#390]
Imagine we have **Author** and **Note**
**Note** can have many **Author**'s and **Author**'s can have many **Note**'s
How to create a **Note** with **Author** = id1 or even **Note** with **Author** = id[1,2] ?
_GET_ with Join works fine, but not _POST_ a **Note** with **Author**'s

**Comment by zMotivat0r** [comment]
```json
{
  ...note props,
  authors(or whatever your authors relation called): [{ ...author object}, {author object}]
}
```
So basically it's the same way as if you programmatically save relational data with TypeOrm. So you can just send a relational object/objects with appropriate entity property name (relation name)

**Comment by bardak-dev** [comment]
> ```
> {
>   ...note props,
>   authors(or whatever your authors relation called): [{ ...author object}, {author object}]
> }
> ```
> 
> 
> So basically it's the same way as if you programmatically save relational data with TypeOrm. So you can just send a relational object/objects with appropriate entity property name (relation name)

Thank you, I’ll try that.
