### ISSUE TITLE
Upgrade to NestJS 6 breaks GET requests

### ISSUE THREAD

**Issue by GillesWHC** [nestjsx/crud#41]
After upgrading to NestJS 6 the generated GET / and GET /:id will always return an empty object.

**Comment by GillesWHC** [comment]
This part seems to be the issue ( taken form [`restful-query.interceptor.ts`](https://github.com/nestjsx/crud/blob/master/src/interceptors/restful-query.interceptor.ts#L35) ).

```
  intercept(context: ExecutionContext, call$: Observable<any>) {
    const req = context.switchToHttp().getRequest();

    req.query = this.transform(req.query);

    return call$;
  }
```

Should be replaced with:

```
  intercept (context: ExecutionContext, next: CallHandler): Observable<any> {
    const req = context.switchToHttp().getRequest();

    req.query = this.transform(req.query);

    return next.handle();
  }

```

as per the [Nest Migration Guide](https://docs.nestjs.com/migration-guide).

@zMotivat0r Do you want me to hotfix this or can you integrate this in the 3.0 release?

**Comment by zMotivat0r** [comment]
@GillesWHC Yes, I know that. I've almost finished v.3.0.0, so will fix that too

**Comment by GillesWHC** [comment]
Great! I'll close this then. Keep up the great work!

**Comment by rhernandez-applaudostudios** [comment]
Is this still happening, I'm in nestjs 6.2.4 and using crud v3.2.0 and I'm getting and empty object for all endpoints, ( get and posts ) also getting a required id field in all swagger documentation endpoints ( this id refers to the path, and should not appear )
