### ISSUE TITLE
how use SELECT COUNT(*) FROM employees? in nestjs crud or AVG, ect...

### ISSUE THREAD

**Issue by dcortesnet** [nestjsx/crud#410]
How can I create my personalized query in order to obtain data in particular as an accountant or averages?

in the documentation I only have this options

query?: {
    allow?: string[];
    exclude?: string[];
    persist?: string[];
    filter?: QueryFilterOption;
    join?: JoinOptions;
    sort?: QuerySort[];
    limit?: number;
    maxLimit?: number;
    cache?: number | false;
    alwaysPaginate?: boolean;
  },

**Comment by Diluka** [comment]
aggregations are not the part of CRUD. so the crud lib doesn't support those functions right now. you need to implement your own routes to do such things.

you can create a query builder by using conditions in `CrudRequest`. see https://github.com/nestjsx/crud/blob/76dc6c2bc841a9b6fdc68b730aa87043f327117b/packages/crud-typeorm/src/typeorm-crud.service.ts#L250-L260
