### ISSUE TITLE
[Question] How to use ParsedBody decorator on custom route

### ISSUE THREAD

**Issue by alexmantaut** [nestjsx/crud#414]
Hi,

I am trying to create a custom POST route to create a effects of creating an entity. (the endpoint needs to be different from the create entity endpoint)

For this I would like to be able to use the ParsedBody decorator to get the body of the entity (see snippet) when I issue a request to this endpoint however, I get an undefined body.

```
@UseInterceptors(CrudRequestInterceptor)
@Post('/preview')
public async previewGroup(@ParsedRequest() req: CrudRequest,
                                            @ParsedBody() dto: AssetGroup, ): Promise<Asset[]> {
```

What I am I doing wrong here? Do I need to add another interceptor or change a config option? I couldn't find anything in the Docs or code to know how to do this.

Thanks in advance

**Comment by zMotivat0r** [comment]
Hi, @alexmantaut 
`@ParsedBody()` is meant to be used for [overridden](https://github.com/nestjsx/crud/wiki/Controllers#routes-override) routes making sure the lib will enable and perform body validation for those routes.
But the lib does nothing with the additional (custom) routes that were added to the crud controller, thus this decorator is useless in those custom routes. Also, please take into account the fact that `ValidationPipe` is being attached per route, not to the whole crud controller.
So, in general, if you need a request body, you need to use `@Body()` decorator from `@nestjs/common`.
If you need a body validation in your custom route, you can follow the suggested NestJs approach ([docs](https://docs.nestjs.com/techniques/validation)).

**Comment by alexmantaut** [comment]
Ah, got it, will use `@Body` plus validation for custom routes.

Thanks for clarifying, I got confused with the `@ParsedBody()` method.

**Comment by Shafik23** [comment]
@zMotivat0r - Your suggestion above still doesn't work for me. I have the following in a User Crud controller:

`  @Post('testing')
  @UsePipes(new ValidationPipe({ transform: true, whitelist: false }))
  testing(@Body() userDto: User) {
    return 'This action adds a new user';
  `
The standard methods (createOne, etc) work fine. Is it not possible to do validation on custom methods inside these Crud controllers?

**Comment by Shafik23** [comment]
@alexmantaut - did you ever get above to work?
