### ISSUE TITLE
How to do a join inside a other join? 

### ISSUE THREAD

**Issue by dcyrillo** [nestjsx/crud#415]
I need to do a join in residence, using the column address and i need to allow only 3 variables. Can someone help me?

```typescript
@Controller('jobs')
@ApiUseTags('jobs')
@Crud({
	model: {
		type: Job,
	},
	query: {
		join: {
			customer: {
				allow: ['id', 'name', 'lastName', 'rating'],
			},
			jobType: {
				allow: ['id', 'name', 'averageTime', 'description'],
			},
			serviceProvider: {
				allow: ['id', 'name', 'lastName', 'rating'],
			},
			residence: {
				allow: ['id', 'nickname', 'addressId'],

			},
		},
	},
})
```

**Comment by zMotivat0r** [comment]
Please, read project's [wiki](https://github.com/nestjsx/crud/wiki/Controllers#join)
Nested joins could be enabled in this way:
```typescript
'residence.address': {
   allow: [...],
},
```

**Comment by dcyrillo** [comment]
cool! 
but it's still doesn't work


@Crud({
	model: {
		type: Job,
	},
	query: {
		join: {
			customer: {
				allow: ['id', 'name', 'lastName', 'rating'],
			},
			jobType: {
				allow: ['id', 'name', 'averageTime', 'description'],
			},
			serviceProvider: {
				allow: ['id', 'name', 'lastName', 'rating'],
			},
			residence: {
				allow: ['id', 'nickname', 'address'],
			},
			'residence.address': {
				allow: ['streetName'],
			},
		},
	},
})

**Comment by dcyrillo** [comment]
cool! But it still doesn't work.
@Crud({
	model: {
		type: Job,
	},
	query: {
		join: {
			customer: {
				allow: ['id', 'name', 'lastName', 'rating'],
			},
			jobType: {
				allow: ['id', 'name', 'averageTime', 'description'],
			},
			serviceProvider: {
				allow: ['id', 'name', 'lastName', 'rating'],
			},
			residence: {
				allow: ['id', 'nickname', 'address'],
			},
			'residence.address': {
				allow: ['streetName'],
			},
		},
	},
})
