### ISSUE TITLE
The inner join is not working

### ISSUE THREAD

**Issue by dcyrillo** [nestjsx/crud#416]
I need to do a join of join inside the query. So i did like in documentation, but it's not working. Can someone can help me?

@Controller('jobs')
@ApiUseTags('jobs')
@Crud({
	model: {
		type: Job,
	},
	query: {
		join: {
			customer: {
				allow: ['id', 'name', 'lastName', 'rating'],
			},
			jobType: {
				allow: ['id', 'name', 'averageTime', 'description'],
			},
			serviceProvider: {
				allow: ['id', 'name', 'lastName', 'rating'],
			},
			residence: {
				allow: ['id', 'nickname', 'address'],
			},
			'residence.address': {
				allow: ['streetName'],
			},
		},
	},
})

**Comment by Diluka** [comment]
> require - should a relation be required or not. For RMDBS means use either INNER or LEFT join. Default: false.

@dcyrillo https://github.com/nestjsx/crud/wiki/Controllers#join
