### ISSUE TITLE
Writing with id only but get complete object 

### ISSUE THREAD

**Issue by Varkal** [nestjsx/crud#417]
Hi

I think to add Crud to my project but want to check if all of my use cases are supported

Did Crud support create/update entities with relation ids, but request them as complete objects ? 

For example, with this entity

```typescript 
class User {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  firstName: string;

  @Column()
  lastName: string;

  @ManyToMany(_type => Role)
  @JoinTable()
  roles: Role[];
}

```

I want to send this body to POST/PUT/PATCH a user (where 1 and 2 are id of valid roles): 

```json
{
    "firstName": "Clara",
    "lastName": "Oswald",
    "roles": [1, 2]
}
```

But get this response on GET requests

```json
{
    "firstName": "Clara",
    "lastName": "Oswald",
    "roles": [{"id": 1, "name": "Human Ressources"}, {"id": 2, "name": "Account Creator"}]
}
```

**Comment by DaVarga** [comment]
Im not sure but i think this should work:

{
    "firstName": "Clara",
    "lastName": "Oswald",
    "roles": [{"id": 1}, {"id": 2}]
}

**Comment by Varkal** [comment]
Thx for your answer. 
But eventually, I've choose to use a Pipe to convert id into their counterpart objects.

**Comment by greenking19** [comment]
Hello, can you tell me your solution? I have the same needs

**Comment by Varkal** [comment]
As Is said previously, i choose to use a Pipe (https://docs.nestjs.com/pipes) to convert the provided ids with their counterparts from the database
