### ISSUE TITLE
Question: CRUD with Webpack compilation

### ISSUE THREAD

**Issue by heuristicAL** [nestjsx/crud#429]
I am trying to use CRUD with Webpack compilation for my Nest Server, currently I get the following error when I try to use Webpack (works fine when NOT using Webpack)
```bash
node_modules/@nestjsx/crud/lib/crud/crud-routes.factory.js:28
[SERVER]         return this.options.model.type.name;
TypeError: Cannot read property 'name' of undefined
[SERVER]     at CrudRoutesFactory.get modelName [as modelName] (long/path/to/project/node_modules/@nestjsx/crud/lib/crud/crud-routes.factory.js:28:40)
```

Any insight into this would be greatly appreciated! Is this a "Just add this to your webpack config" kind of thing? 😄

**Comment by Diluka** [comment]
in `nest-cli.json`
```json
{
  "compilerOptions": {
    "webpack": false
  }
}
```

webpack will pack the project into a single js file. If there is some code trying to work depending on path, the structure of the source code, will not work.

maybe you are using some libs which are scanning folders.

trying turn off webpack see if it is working.

**Comment by heuristicAL** [comment]
I can confirm that everything works if I'm not using webpack as that was what I was doing beforehand. I was trying to get webpack to work to benefit from Hot Module Reloading. So in your opinion this is not a problem caused by CRUD?

**Comment by Diluka** [comment]
Maybe. Libs use reflections may not work in webpack.

**Comment by heuristicAL** [comment]
Guess that explains it! So CRUD requires no webpacking to work 🙂
