### ISSUE TITLE
JWT Token CRUD

### ISSUE THREAD

**Issue by WilliamKrieg** [nestjsx/crud#439]
Hello,
I don't understand how to secure my endpoint with an jwt authentifcation ?
It's possible with your crud solution ?

I am a bit lost in your documentation.

Thanks

**Comment by alexmantaut** [comment]
Hi @WilliamKrieg:

I use jwt authentication on my crud controllers. Jwt authentication can be implemented using NestJs guards. 

To implement auhentication, you basically need to implement a Guard to get the token and validate it, and then inject that guard for the controllers that need to be authenticated.

How to implement the jwt guard can be found [here](https://docs.nestjs.com/techniques/authentication) (It explains how to create the guard + install necessary dependencies.)

To inject the guard on your CRUD controller:
```
@Crud({
  model: {
    type: Event,
  },
})
@UseGuards(
  AuthGuard('jwt'),
  // Other guards
)
```
I hope it helps,

**Comment by sebinq** [comment]
And then you can also specify guard for specific CRUD route using:

```ts
@Crud({
  model: { type: Event },
  routes: {
    createOneBase: {
      decorators: [UseGuards(AuthGuard('jwt'))],
    },
    updateOneBase: {
      decorators: [UseGuards(AuthGuard('jwt'))],
    },
  },
})
```
