### ISSUE TITLE
Swagger type for paginated getMany results

### ISSUE THREAD

**Issue by mkolbusz** [nestjsx/crud#448]
Is it possible to set custom type for items in swagger documentation for `getMany` paginated results? I have a model with `id` field that should not be visible in swagger for `POST createOne` but should be visible while `GET getMany`. But when I set `@ApiOkResponse({ type: [ModelWithId] })` for `getMany` I loose the pagination data from `getMany`. Is here any solution?
Thanks!

**Comment by zMotivat0r** [comment]
Yes, you can use [serialize](https://github.com/nestjsx/crud/wiki/Controllers#serialize) option since Swagger response models are taken from there

**Comment by mkolbusz** [comment]
Thanks for the response! I have another question related to the previous one. Is it possible to set `getMany` response type using the default `GetManyDefaultResponse` interface? I used:
```
@Crud({
  serialize: {
    getMany: GetManyDefaultResponse<GetManyTimelineEventResponse>
  }
})
```
but it is not valid usecase of the `GetManyDefaultResponse` interface.
Do I need to create a class with the paginated structure and generic type for that?
