### ISSUE TITLE
[DOC] Add some documentation about SFieldOperator

### ISSUE THREAD

**Issue by maximelafarie** [nestjsx/crud#451]
I'm working on some requests filtering, and it is really painful to understand what each operator is doing and what it does. Here's the entire Field Operators:

```typescript
export declare type SFieldOperator = {
    $eq?: SFiledValues;
    $ne?: SFiledValues;
    $gt?: SFiledValues;
    $lt?: SFiledValues;
    $gte?: SFiledValues;
    $lte?: SFiledValues;
    $starts?: SFiledValues;
    $ends?: SFiledValues;
    $cont?: SFiledValues;
    $excl?: SFiledValues;
    $in?: SFiledValues;
    $notin?: SFiledValues;
    $between?: SFiledValues;
    $isnull?: SFiledValues;
    $notnull?: SFiledValues;
    $eqL?: SFiledValues;
    $neL?: SFiledValues;
    $startsL?: SFiledValues;
    $endsL?: SFiledValues;
    $contL?: SFiledValues;
    $exclL?: SFiledValues;
    $inL?: SFiledValues;
    $notinL?: SFiledValues;
    $or?: SFieldOperator;
    $and?: never;
}
```
So adding a bit of documentation about that would be awesome, but I can't contribute since I can't suggest changes on the wiki. If you want me to contribute or do some code feel free to ask me for it! 🤓 

Btw, adding a concrete example about each operator could be useful too.

Awesome work tho. 🖖 

**EDIT**:
Ok so I got some more clues about the meaning of each operator (but it really should be mentioned in the doc). So I'm putting it below in order to help some people in the same case than me:

```typescript
export enum CondOperator {
  EQUALS = '$eq',
  NOT_EQUALS = '$ne',
  GREATER_THAN = '$gt',
  LOWER_THAN = '$lt',
  GREATER_THAN_EQUALS = '$gte',
  LOWER_THAN_EQUALS = '$lte',
  STARTS = '$starts',
  ENDS = '$ends',
  CONTAINS = '$cont',
  EXCLUDES = '$excl',
  IN = '$in',
  NOT_IN = '$notin',
  IS_NULL = '$isnull',
  NOT_NULL = '$notnull',
  BETWEEN = '$between',
  EQUALS_LOW = '$eqL',
  NOT_EQUALS_LOW = '$neL',
  STARTS_LOW = '$startsL',
  ENDS_LOW = '$endsL',
  CONTAINS_LOW = '$contL',
  EXCLUDES_LOW = '$exclL',
  IN_LOW = '$inL',
  NOT_IN_LOW = '$notinL',
}
```

**Comment by zMotivat0r** [comment]
@maximelafarie actually, they are documented [here](https://github.com/nestjsx/crud/wiki/Requests#filter-conditions)

**Comment by maximelafarie** [comment]
Oh right, thank you I missed that part!
My bad!
