### ISSUE TITLE
ERROR: missing ) after argument list when running `yarn bootstrap`

### ISSUE THREAD

**Issue by ruslanguns** [nestjsx/crud#455]
I am getting an issue when running `yarn start:typeorm` 

![image](https://user-images.githubusercontent.com/19806968/77424408-fb95b280-6dc8-11ea-9c25-134719ed92a0.png)

```
[System Information]
OS Version     : Windows 10
NodeJS Version : v12.16.0
NPM Version    : 6.14.3

[Nest CLI]
Nest CLI Version : 7.0.2
```
I fix it in the PR #454

**Comment by zMotivat0r** [comment]
So I suppose it's a Windows-only issue? I'll test your PR, thanks.

**Comment by ruslanguns** [comment]
@zMotivat0r not sure... but yes I do use Windows as my dev machine!

**Comment by zMotivat0r** [comment]
fixed with https://github.com/nestjsx/crud/compare/v4.4.2...v4.4.3
