### ISSUE TITLE
Forbid to POST with 'id' set

### ISSUE THREAD

**Issue by sebinq** [nestjsx/crud#461]
Hello!

So, I've created my BaseEntity, which is defined by following declaration:

```ts
import {
  Entity,
  BaseEntity as TypeormBaseEntity,
  Column,
  PrimaryGeneratedColumn,
} from 'typeorm';
...
const { CREATE } = CrudValidationGroups;

@Entity()
export class BaseEntity extends TypeormBaseEntity {
  @ApiProperty()
  @IsEmpty({ groups: [CREATE] })
  @PrimaryGeneratedColumn()
  id: number;

  @ApiProperty()
  @Column({
    default: () => 'UTC_TIMESTAMP()',
  })
  createdAt: string;

  @ApiProperty()
  @Column({
    default: () => 'UTC_TIMESTAMP()',
  })
  modifiedAt: string;
}
```

Whole point of this issue is that now, I keep getting `{"statusCode":400,"message":["id must be empty"],"error":"Bad Request"}` not only when I use POST request, but also when PUT/PATCH reuqest are sent.

I've read something about globally set ValidationPipe from `main.ts` can break CRUD validation pipe, so I've tried to remove my own ValidationPipe, but result is still same.

I was wondering if there is someone who can point me to the right direction to solve my issue. 
Thank you so much!

**Comment by sebinq** [comment]
Btw my goal is to forbid user to set "id" during post request so he can't override some other record in database.

**Comment by markonyango** [comment]
In my opinion the 400 error is justified:

You are replacing/updating all/some attributes of your entity but you are not creating a new entity => id should stay the same and remain immutable.

**Comment by sebinq** [comment]
It should but in current version, if I send POST on CRUD endpoint with id field, it will create a new record with id from request.

This behaviour is simply bad, because you can overwrite any other record that is currently in tour Database.

**Comment by zMotivat0r** [comment]
@sebinq can you show me the `TypeormBaseEntity` please?
I'm trying to reproduce your issue currently

**Comment by zMotivat0r** [comment]
@sebinq  I can confirm that entity validation rules work when you remove with the global ValidationPipe enabled.
Please take a look at this [example](https://github.com/nestjsx/crud/pull/480/files) - it prevents saving `id` on `POST` and allows saving it on `PATCH`/`PUT`.

**Comment by sebinq** [comment]
my `TypeormBaseEntity` is just named BaseEntity import. Ok, I will take a look and let you know if there is any other problem :) thanks.
