### ISSUE TITLE
Swagger Models is empty

### ISSUE THREAD

**Issue by zerox12311** [nestjsx/crud#47]
Hello~
I use this library and with swagger
I create a User entity with id and name fields
But I found the Models in swagger will shown User Model, but no any field in it.
How to fix it?
Thanks!

**Comment by zMotivat0r** [comment]
Hi. You need to apply `@ApiModelProperty()` decorator for your entity fields. Please refer to this [doc](https://docs.nestjs.com/recipes/swagger).

**Comment by Diluka** [comment]
If you are using `class-validator` you can do this trick with [`class-validator-jsonschema`](https://github.com/epiphone/class-validator-jsonschema) :)
```ts
  const document = SwaggerModule.createDocument(app, options);
  const metadatas = (cv.getFromContainer(cv.MetadataStorage) as any).validationMetadatas;
  const schemas = validationMetadatasToSchemas(metadatas, {
    refPointerPrefix: '#/definitions/',
  });
  _.defaultsDeep(document.definitions, schemas);
```

see this https://www.npmjs.com/package/routing-controllers-openapi#validation-classes

**Comment by anthony-bernardo** [comment]
How to manage this in 2023 ? I have the same issue

**Comment by anthony-bernardo** [comment]
in 2023, is there a way to automatically expose field of entities without usage of `@ApiProperty()` ?

**Comment by outp1** [comment]
> in 2023, is there a way to automatically expose field of entities without usage of `@ApiProperty()` ?

+. I also need this feature!
