### ISSUE TITLE
[Question] Document Params with Enum Value?

### ISSUE THREAD

**Issue by tbrannam** [nestjsx/crud#471]
Is there a pattern that would support documenting valid values for a parameter - such that Swagger UI will display Enum Values (a select input)?   With standard nest controller logic - the `@ApiParam` exposes {enum: ECategory} as an option.   It seems like one would have to override all the operations in order to decorate them directly.

```
@Crud({
  model: {
    type: Category
  },
  params: {
    categoryId: {
      field: 'category',
      type: 'string',
      //enum: CategoryEnum // given an Enum CategoryEnum - it would be nice to be able to pass this to Swagger-UI
    }
  }
})```

**Comment by tbrannam** [comment]
#472 tried to resolve this issue

**Comment by zMotivat0r** [comment]
Thanks for your issues and PR. I'll check it and merge if everything is good

**Comment by zMotivat0r** [comment]
#472 merged
