### ISSUE TITLE
Any way to include Request query parameters in Swagger Docs?

### ISSUE THREAD

**Issue by jeffreyschultz** [nestjsx/crud#484]
The wiki has documentation of the possible query params that can be sent to a controller to handle things like filtering, selecting, joining, etc., but I don't see any of it in the Swagger docs. I would have imagined this would be something that could and should be automatically inserted.

https://github.com/nestjsx/crud/wiki/Requests#query-params

**Comment by zMotivat0r** [comment]
This functionality is already included.
Have you connected swagger properly? What's the version of the nest swagger package?

**Comment by zMotivat0r** [comment]
Please take a look at the [example project](https://github.com/nestjsx/crud/wiki#running-an-example-project)

**Comment by jeffreyschultz** [comment]
This isn't showing up in my app, but it is in the integration project. I will see what I am doing wrong.

Thanks.
