### ISSUE TITLE
Any way to navigate an entity using the Controller route?

### ISSUE THREAD

**Issue by jeffreyschultz** [nestjsx/crud#485]
Currently, I have a simple set of entities set up with nestjsx/crud, and it generates the CRUD operations for me and exposes them through the controller. Nice.

What I am curious about is if there is support for navigating the entity using the route? Say for instance, I have a Document that is associated with a Package, where the Package is a @ManyToOne within the Document as `package`. Could I fetch only the package for the document using something like `/documents/101/package`?

**Comment by zMotivat0r** [comment]
Apparently you need to create another controller to do so. Please take a look at the [example project](https://github.com/nestjsx/crud/wiki#running-an-example-project)
