### ISSUE TITLE
Support custom ORM

### ISSUE THREAD

**Issue by lukasfrana** [nestjsx/crud#486]
Is there any way how to use custom ORM? Due to paused development on TypeORM we are moving to [MikroORM](https://github.com/mikro-orm/mikro-orm). I haven't found mention about custom ORMs in docs. My idea is that I would implement CrudService interface in my service ad then use it in @Crud in controller. Is that possible?

**Comment by zMotivat0r** [comment]
Yes, it's possible. Your service must extend this [abstract class](https://github.com/nestjsx/crud/blob/master/packages/crud/src/services/crud-service.abstract.ts) and implement its abstract methods and you good to go to use it as your service in crud controllers.
