### ISSUE TITLE
[Questio] Admin panel

### ISSUE THREAD

**Issue by muturgan** [nestjsx/crud#490]
Hello dear team.
This project is amasing!
Do you plan to provide an admin panel?

**Comment by zMotivat0r** [comment]
Hi, no I don't plan to provide the admin panel.
You can use https://marmelab.com/react-admin/ with nestjsx/crud data-provider https://github.com/FusionWorks/react-admin-nestjsx-crud-dataprovider

**Comment by muturgan** [comment]
> Hi, no I don't plan to provide the admin panel.
> You can use https://marmelab.com/react-admin/ with nestjsx/crud data-provider https://github.com/FusionWorks/react-admin-nestjsx-crud-dataprovider

it's preatty good
thank you!
