### ISSUE TITLE
E2E: Builder.search is not a function

### ISSUE THREAD

**Issue by akshay-sourcefuse** [nestjsx/crud#495]
I'm trying to perform e2e testing using this [guide](https://github.com/nestjsx/crud/blob/master/packages/crud-typeorm/test/c.basic-crud.spec.ts).

Since my API endpoints are protected by JWT, I've used `AuthGuard('jwt')` as **JwtAuthGuard** class.
So, I've overridden the guard to use the custom value using this [SO answer](https://stackoverflow.com/a/57660805/5016871).

But whenever I call the API through supertest, I'm getting _Internal Server Error_ and `builder.search is not a function` as stack trace.

Here is my TestingModule.
```
fdescribe('Events Controller (e2e)', () => {
    let app: INestApplication;
    let qb: RequestQueryBuilder;

    beforeAll(async () => {
        const moduleRef: TestingModule = await Test.createTestingModule({
            imports: [
                TypeOrmModule.forRoot(),
                JwtModule.register({
                    secret: process.env.JWT_SECRET,
                }),
                HttpModule,
                ...moreProviders
            ],
            controllers: [EventsController],
            providers: [
                EventsService,
                UsersService,
                JwtStrategy,
                {
                    provide: getRepositoryToken(User),
                    useClass: MockRepository,
                },
                {
                    provide: getRepositoryToken(Events),
                    useClass: MockRepository,
                },
                ...moreRepositories
            ],
        })
            .overrideGuard(JwtAuthGuard)
            .useValue({
                canActivate: (context: ExecutionContext) => {
                    const req = context.switchToHttp().getRequest();
                    req.user = userObject;
                    return true;
                },
            })
            .compile();
        app = moduleRef.createNestApplication();
        await app.init();
    });

    beforeEach(() => {
        qb = RequestQueryBuilder.create();
    });

    afterAll(async () => {
        await app.close();
    });

    it(`/GET events`, async () => {
        return request(app.getHttpServer())
            .get('/events')
            .expect(({ error }) => {
                console.log(error);
            });
    });
```

Here is the stack trace:

> [Nest] 6861   - 05/04/2020, 23:07:09   [ExceptionHandler] builder.select is not a function
> TypeError: builder.select is not a function
>     at EventsService.createBuilder (/home/akshay/Documents/haskell_api/node_modules/@nestjsx/crud-typeorm/src/typeorm-crud.service.ts:272:13)
>     at EventsService.getMany (/home/akshay/Documents/haskell_api/node_modules/@nestjsx/crud-typeorm/src/typeorm-crud.service.ts:89:32)
>     at EventsService.getMany (/home/akshay/Documents/haskell_api/src/events/services/events.service.ts:147:37)
>     at EventsController.getMany (/home/akshay/Documents/haskell_api/src/events/controllers/events.controller.ts:131:29)
>     at /home/akshay/Documents/haskell_api/node_modules/@nestjs/core/router/router-execution-context.js:37:29
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)

Any resolution to this problem?

Thanks.

Edit: I've mocked the repository (`MockRepository`) using this [link](https://github.com/nestjsx/crud/issues/325#issuecomment-566666542)

**Comment by zMotivat0r** [comment]
>Any resolution to this problem?

Yes, sure:

1. Read an error:

>TypeError: builder.select is not a function
at EventsService.createBuilder (/home/akshay/Documents/haskell_api/node_modules/@nestjsx/crud-typeorm/src/typeorm-crud.service.ts:272:13)

2. Go to the `@nestjsx/crud-typeorm/src/typeorm-crud.service.ts:272:13` as it says. Here it is:
https://github.com/nestjsx/crud/blob/7ef9744013b4b690fad667ddff089dc9135454d2/packages/crud-typeorm/src/typeorm-crud.service.ts#L272
And you'll notice that it's in this method:
https://github.com/nestjsx/crud/blob/7ef9744013b4b690fad667ddff089dc9135454d2/packages/crud-typeorm/src/typeorm-crud.service.ts#L262

3. Compare it with this mock that you're using:
>Edit: I've mocked the repository (MockRepository) using this link

You should notice that it doesn't mock `createBuilder` method.

You're welcome.
Cheers
