### ISSUE TITLE
BUG in filter with multiple OR condition

### ISSUE THREAD

**Issue by mateus96mt** [nestjsx/crud#497]
When we filter using only one or condition it works perfectly, but adding an addition OR the return is not correct.

Example: 

using only filter + or, it works correctly.

```
&filter=customer.name||$contL||"SEARCH"&or=customer.lastName||$contL||"SEARCH"
```

adding a new OR condition the return is as if the last or condition is ignored, the last condition is not filtered.

```
&filter=customer.name||$contL||"SEARCH"&or=customer.lastName||$contL||"SEARCH"&or=jobType.name||$contL||"SEARCH"
```

Thanks in advanced!

**Comment by zMotivat0r** [comment]
[docs](https://github.com/nestjsx/crud/wiki/Requests#or) says: 

> If present both or and filter in any amount (one or miltiple each) then both interpreted as a combitation of AND conditions and compared with each other by OR condition, as follows:
WHERE ({filter} AND {filter} AND ...) OR ({or} AND {or} AND ...)

Also, `filter` and `or` query params will be deprecated and removed in one of the next major releases. A [search](https://github.com/nestjsx/crud/wiki/Requests#search) was introduced in recent versions to replace them. I will no longer maintain `filter` and `or` query params functionality. Please, consider using `search` instead. Thanks
