### ISSUE TITLE
[Request] Support for all typeOrm entity events (beforeUpdate etc)

### ISSUE THREAD

**Issue by jbjhjm** [nestjsx/crud#51]
Hi there, I was trying to implement some entity property modification method.
In this case, I was going to use @BeforeInsert and @BeforeUpdate decorators to add functionality to my entity to check if a new password was given, and if so, to hash it.

I have found a workaround by using @Override updateOne in controller.
But... I think it would be great if crud would support the entity events entirely. 

What do you think about that? Are there plans to support these?

**Comment by zMotivat0r** [comment]
Hi.
>But... I think it would be great if crud would support the entity events entirely.
I'll test those decorators, but I don't think that crud is actually has something to do with that because it's tataly the TypeORM's area of ​​responsibility, don't you think?

**Comment by jbjhjm** [comment]
> Hi.
> 
> > But... I think it would be great if crud would support the entity events entirely.
> 
> I'll test those decorators, but I don't think that crud is actually has something to do with that because it's totally the TypeORM's area of ​responsibility, don't you think?

Thanks - I have to admit I did not deep dive into how crud interacts with typeOrm by now.
If crud is actually making use of regular typeOrm update method, I guess you are right and the issue is related to the latter one.

**Comment by quentin-vauban** [comment]
I would love to be able to use typeorm decorators such as @BeforeInsert, @BeforeUpdate and @AfterLoad.

Cheers

**Comment by lapwat** [comment]
I would love to be able to use typeorm decorators such as @BeforeInsert, @BeforeUpdate and @AfterLoad.
Cheers

**Comment by zMotivat0r** [comment]
@lapwat `repo.update` will not update relational resources but `repo.save` will do. That's why `save` has been chosen over `update`

**Comment by quentin-vauban** [comment]
@BeforeUpdate is not triggered by .updateOneBase

**Comment by lapwat** [comment]
@BeforeUpdate is not triggered by .updateOneBase
