### ISSUE TITLE
Serverless `filter` query params throws preflight response cors issue

### ISSUE THREAD

**Issue by rainercedric23** [nestjsx/crud#513]
currently implementing CRUD controller onto my new methods when I stumbled upon this message

> Access to XMLHttpRequest at 'https://my.environment-api.com/comment?sort=createdAt,DESC&filter=revisionId||$eq||2' from origin 'https://my.environment-fe.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

but when remove the `filter` params, the error goes away, we are currently implementing a `aws-serverless-express` onto our NestJS APIs and we would like to know if this is a current problem/issue here.

Note: everything is working fine when I am implementing it on my local (I think because it was running it's own Node JS server) 

is it related to this one: https://github.com/awslabs/aws-serverless-express/issues/214 ?

**Comment by zMotivat0r** [comment]
yes, it is, and it's already been mentioned here https://github.com/nestjsx/crud/issues/313

**Comment by pejulian** [comment]
Hello, is there some workaround that can be used while waiting for this issue to be fixed?
