### ISSUE TITLE
Cannot hide relation primary key from HTTP Get route when using joins

### ISSUE THREAD

**Issue by phils-hub** [nestjsx/crud#514]
I have an ItemsController:
````js
@Crud({
  model: { type: Item },
  ...
  query: {
    join: {
      owner: {
        allow: [ "name" ]
      }
    }
  },
  serialize: {
    get: ItemResponseDto
  }
})
````
If I have the following DTOs:
````
export class ItemResponseDto {
  @Expose()
  title: string
  ...
  @Expose()
  owner?: OwnerDto
}
export class OwnerDto {
  @Expose()
  name: string
}
````
Then running the query `curl -X GET "http://localhost:3000/items/5?join=owner` will return the id of the Owner Entity, even though:
* I only exposed "name" in the DTO
* I only allowed "name" in the controller

Is there a workaround? Am I missing something?

Note that the entity _Item_ inherits the _id_ primary generated column from a _BaseEntity_. It seems this issue only applies to primary keys, as CreatedDateColumn and UpdateDateColumn entity attributes are not "leaked".

**Comment by zMotivat0r** [comment]
You need to use `Type` decorator from `class-transformer` package

```typescript
export class ItemResponseDto {
  @Expose()
  title: string
  ...
  @Expose()
  @Type(t => OwnerDto)
  owner?: OwnerDto
}
export class OwnerDto {
  @Expose()
  name: string
}
```
