### ISSUE TITLE
@ApiHideProperty on crud param still showing up in swagger doc

### ISSUE THREAD

**Issue by darrenjennings** [nestjsx/crud#517]
I am trying to use `@ApiHideProperty()` for swagger docs https://docs.nestjs.com/recipes/swagger#decorators but a param is always showing up because it is specified in the Crud decorator. My configuration:

```ts
@OrganizationGuard
@Crud({
  model: {
    type: ServicePackage
  },
  params: {
    organization: { // field I want to hide from docs
      field: 'org',
      type: 'string'
    },
    ...
  }
  ...
})
```

This is so that I can filter the `ServicePackage` entity by organization, but this param is provided by `@OrganizationGuard` which intercepts requests and adds the `organization` param to the request before Crud executes the query.

```ts
@Injectable()
export class OrganizationGuard implements CanActivate {
  canActivate (context: ExecutionContext): boolean {
    const request = context.switchToHttp().getRequest()
    if (request?.user?.org?.id) {
      request.params.organization = request.user.org.id

      return true
    }

    return false
  }
```

This means that the endpoints must have `organization` required, but I want to communicate to the docs that it is not required.

**Comment by zMotivat0r** [comment]
This doesn't seem to have any sense to me. You're setting up a path param which is not allowed to be filled in. So why would you even set it up then? If it should always be equal to `user.org.id`then you don't need it in your URL.

All you need is `@CrudAuth` decorator ([docs](https://github.com/nestjsx/crud/wiki/Controllers#request-authentication))

```typescript
@CrudAuth({
  property: 'user',
  filter: (user: User) => ({
    org: user.org.id,
  })
})
```

and to change OrganizationGuard to look like this:

```typescript
@Injectable()
export class OrganizationGuard implements CanActivate {
  canActivate (context: ExecutionContext): boolean {
    const request = context.switchToHttp().getRequest()
    return request?.user?.org?.id ? true : false;
  }
```

**Comment by darrenjennings** [comment]
@zMotivat0r wow thank you so much... this makes way more sense and works perfectly.

**Comment by darrenjennings** [comment]
@zMotivat0r how would I make sure that POST requests also have the org associated from the User without needing to specify in a param? seems like filter only works on querying existing entities?

**Comment by darrenjennings** [comment]
btw, I am able to hook into the post action but it looks a bit verbose / and maybe not the best... I will try and extract this to a Decorator for usage in other entities and on the other endpoints ('createMany', `delete`, 'update` etc.), unless you have any recommendations

```ts
@Override('createOneBase')
  create (@ParsedRequest() request: CrudRequest, @ParsedBody() dto: ServicePackage, @Request() req) {
    request.options.params.org = {
      field: 'org',
      type: 'string'
    }
    dto.org = new Organization()
    dto.org.id = req.user.org.id
    return this.base.createOneBase(request, dto)
  }
```

**Comment by zMotivat0r** [comment]
You can use `persist` function in `@CrudAuth` decorator. Please, read the wiki

**Comment by darrenjennings** [comment]
@zMotivat0r sorry still new to the framework, so was not immediately obvious that persist is able to handle this.
