### ISSUE TITLE
Nested Controller parent param filter not working

### ISSUE THREAD

**Issue by seangal2** [nestjsx/crud#520]
We are trying to have a nested controller for two objects:
ProjectEntity
|--- InputEntity

When trying to send a GET request we get the following response:
`column InputEntity.projectId_id._id does not exist`

Here is my controller:
```typescript
@Crud({
  model: {
    type: InputEntity
  },
  params: {
    projectId: {
      field: 'projectId',
      type: 'uuid'
    },
    id: {
      field: '_id',
      type: 'uuid',
      primary: true
    }
  }
})
@ApiTags('inputs')
@Controller('project/:projectId/inputs')
export class InputController {
```

The entity relation is defined as:
```typescript
@ManyToOne(
    type => ProjectEntity,
    (project: ProjectEntity) => project.inputs,
    { onDelete: 'CASCADE' }
  )
  @ApiPropertyOptional()
  projectId: ProjectEntity;
```

We had this code working a few weeks ago, but we tried multiple versions of this package, typeorm and postgres and can't get it to work again.

After digging in into the code of NestJSX/curd we found that the resulting query has:
```sql
... WHERE ("InputEntity"."projectId_id._id" = $1)
```

And we try to execute it in a SQL editor and it is not a valid query.
Without the `._id` part the query works.

The strange field comes from `entityColumnsHash` where in the initialization it thinks it is an embedded type (but it is stored as a simple ID string)

We will be thankful if this problem will be resolved as we can't find a way to deploy our system in the present time.

**Comment by zMotivat0r** [comment]
Yes, while fixing filtering by relations and especially nested relations, I've changed a join relation internal mechanism, and actually I'm really surprised why this thing that you've described worked earlier because it looks wrong to me though - you've trying to filter by a relation name directly but not by either an entity name or a joint relation column name. Again, it's very weird and not an intended behavior but rather a side effect of the bug we had earlier.

So, I see two possible solutions here. You can do one of these:

1. First option: add a `projectId_id` column to the entity:

```typescript
@Column()
projectId_id: string
```

and change your param field name in the controller:

```typescript
projectId: {
    field: 'projectId_id',
    type: 'uuid'
},
```

2. Second option: join this `projectId` relation and filter by its `_id` column:

```typescript
@Crud({
  model: {
    type: InputEntity
  },
  query: {
    join: {
      projectId: {} // join this relation
    }
  },
  params: {
    projectId: {
      field: 'projectId._id', // filter by a joint relation column 
      type: 'uuid'
    },
    id: {
      field: '_id',
      type: 'uuid',
      primary: true
    }
  }
})
```

Also, let me notice something - usually, a relation name in your case will be `project` but not `projectId` which confused me a little bit when I first saw this.

**Comment by seangal2** [comment]
Hi,
Thanks for the quick response!

We chose to go with option 2 since we have some other complex queries that use this relations. I agree that the naming of this field is miss-leading, we named it this way because we saw that in the DB the id is stored there, and this is probably why the params worked before.

Your solution worked, but we had to add `eager: true` to make it work. However this causes the response to include the parent object data as well, and we don't want it to. **Is there a way to make it work without sending this data?**

Thanks again.

**Comment by seangal2** [comment]
We have discovered another problem with the solution.

This solution makes the GET requests somewhat work, but it breaks the POST requests, as the created resources don't have their `projectId` set (it is saved with `null`).

**Comment by zMotivat0r** [comment]
Read the query join docs please. You need to set up `required: false` and `select: false`

**Comment by avmraa** [comment]
Encountered the same issue -different routes worked and failed depending on the params field mapping. The workaround is to define 2 controllers for the same path with different routes options:
```
@Crud({
  model: {
    type: Preference,
  },
  params: {
    clientId: {
      field: 'client',
      type: 'number',
      primary: false,
    },
  },
  query: {
    join: {
      client: {
        eager: true,
        select: false,
      },
    },
  },
  routes: {
    only: ['createManyBase', 'createOneBase', 'replaceOneBase'],
  },
})
@Controller('clients/:clientId/preferences')
export class PreferencesController1 implements CrudController<Preference> {
  constructor(public service: PreferenceService) {}
}

@Crud({
  model: {
    type: Preference,
  },
  params: {
    clientId: {
      field: 'client.id',
      type: 'number',
      primary: false,
    },
  },
  query: {
    join: {
      client: {
        eager: true,
        select: false,
      },
    },
  },
  routes: {
    only: ['getOneBase', 'getManyBase', 'deleteOneBase', 'updateOneBase'],
  },
})
@Controller('clients/:clientId/preferences')
export class PreferencesController2 implements CrudController<Preference> {
  constructor(public service: PreferenceService) {}
}

```
looks ugly but works. This is apparently a bug in the library.
