### ISSUE TITLE
GetMany() filter

### ISSUE THREAD

**Issue by crismcn** [nestjsx/crud#522]
![i](https://user-images.githubusercontent.com/43445354/82620749-df1cc780-9c0b-11ea-88fe-3184aba6a71d.png)
I want the requested field to be in the entity class. Whether there is a decorator to solve the problem.

**Comment by zMotivat0r** [comment]
As I can see, your entity doesn't have `age` column so you need to add it apparently

**Comment by crismcn** [comment]
Hello, I want to ask how can I avoid this error if the entity class does not have this parameter `age`

**Comment by zMotivat0r** [comment]
Oh, I got you.
So, basically, this error is thrown by TypeOrm but you can catch it a [Exception filter](https://docs.nestjs.com/exception-filters) but it's not a nestjsx/crud issue - it's totally your business logic implementation. So it's totally up to you.
