### ISSUE TITLE
Disable param for custom route

### ISSUE THREAD

**Issue by VyacheslavSaloidWork** [nestjsx/crud#524]
Hey

How can i disable id param for my custom route? 

```
  params: {
    id: {
      field: 'id',
      type: 'uuid',
      primary: true
    }
  },
```

```
  @Get('count')
  getCount() {
    return this.service.getCount();
  }
```

But, i got _Invalid param id. UUID string expected_ on GET /count

**Comment by hakimassouane2** [comment]
Is there any answer to this please ? i'm facing the same issue with a custom route along with the override of the getOne route
