### ISSUE TITLE
CRUD Filter do not distinct type, eg 'a||$eq||1'

### ISSUE THREAD

**Issue by longweiquan** [nestjsx/crud#532]
Hello,

First of all, thank you for providing such a good library to simplify the daily development, I love this utils very much. I hope this issue could help you improve the library.

The CRUD Provide two query way: search and filter.

search is a json object in string form, and filter has special syntax like "a||$eq||1".

The above example will run in wrong where a is number type. because filter parser do not distinguish the field's value type and affect always string as value '1', witch will make Typeorm run in error.

search don't have this problem because it's in json form and it can get back its original type.

I suggest to amend the filter syntax by allowing '' in the string like "a||$eq||'1'"

**Comment by zMotivat0r** [comment]
Filters and search params are being parsed by a parser and if you send `a||$eq||1` it will be parsed to `[ { field: 'id', operator: '$eq', value: 1 } ]`
![Снимок экрана 2020-06-06 в 15 03 41](https://user-images.githubusercontent.com/5868830/83943786-55721a00-a807-11ea-96f6-89ef5d3ab50e.png)
![Снимок экрана 2020-06-06 в 15 03 57](https://user-images.githubusercontent.com/5868830/83943788-5b67fb00-a807-11ea-93f3-49621bd614c1.png)
<img width="1501" alt="Снимок экрана 2020-06-06 в 15 04 19" src="https://user-images.githubusercontent.com/5868830/83943790-5f941880-a807-11ea-8398-68793151906c.png">
So what exact problem do you have?
Can you show me some logs, sql, screenshots?

**Comment by longweiquan** [comment]
@zMotivat0r ,

Sorry that I've given a wrong example, the integer works very well, its the string value that do not work. for example :

filter = 'keyString||$eq||1'

in this case, the parsed filter will be

[ { field: 'keyString', operator: '$eq', value: 1}] 

but the keyString field accept only string, witch will then generate an error in typeorm level.

thanks

**Comment by zMotivat0r** [comment]
Ok, understood.
This was one of the reasons why `search` param was developed. So as I mentioned in this [comment](https://github.com/nestjsx/crud/issues/497#issuecomment-624449213), `filter` and `or` params are gonna be deprecated in the next major releases. So, please consider using `search` instead

**Comment by laudibert** [comment]
@zMotivat0r would you consider adding in the docs that `filter`and `or` will be deprecated ? I randomly found this information but I think it is rather important.

PS: thanks for this great project.
