### ISSUE TITLE
[Help] Is there a way to set default join?

### ISSUE THREAD

**Issue by Bnaya** [nestjsx/crud#54]
I want some of my entities to make specific joins by default.
is there a way to declare that?

**Comment by zMotivat0r** [comment]
I think you can do that at an Entity level. But CRUD lib doesn't have such functionality yet.

**Comment by zMotivat0r** [comment]
Yep, keep it, please. Will add this as a feature. Thanks!

**Comment by Bnaya** [comment]
Thank you!

**Comment by zMotivat0r** [comment]
@Bnaya please see the [docs](https://github.com/nestjsx/crud/wiki/Controllers#join)
