### ISSUE TITLE
Throw Bad Request instead of Internal Server Error for not existing Foreign Key and Unique Key

### ISSUE THREAD

**Issue by kafai97** [nestjsx/crud#544]
nestjsx/crud will throw 500 Internal Server Error when I create/update data in these 2 cases.

- Duplicate Unique Key
```typescript
@Entity()
export class User {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column({ unique: true })
  name!: string;
}
```

- Not Existing Foreign Key
```typescript
@Entity()
export class Department {
  @PrimaryGeneratedColumn()
  id!: number;

  @OneToMany(type => User)
  users: User[]
```

Those two cases were so often to happen but haven't be handled well under this package.

For now, I need to override `createOneBase`/`updateOneBase` method. I think default to throw bad request will be better than Internal Server Error.

**Comment by duongle26** [comment]
Is there any way other than overriding?

**Comment by zMotivat0r** [comment]
@duongle26 NestJs way is to use [Exception filters](https://docs.nestjs.com/exception-filters)

**Comment by duongle26** [comment]
@zMotivat0r but I have to override the method, use try-catch to catch the error, and then throw an Exception. Could you provide an example of a better way to handle this?

**Comment by cgm164** [comment]
A possible solution is to catch every unhandled exception as an application filter and re-throw the error according to the typeorm's error. An example can be found here:
https://stackoverflow.com/a/67556738
