### ISSUE TITLE
Error to Return one List 

### ISSUE THREAD

**Issue by dcyrillo** [nestjsx/crud#549]
When I try to get the list it happens 
{
    "statusCode": 400,
    "message": "Invalid param id. UUID string expected",
    "error": "Bad Request"
}
@Crud({
	model: {
		type: BankAccount,
	},
	query: {
		join: {
			bank: {},
			serviceProvider: {
				allow: ['id', 'name', 'lastName', 'rating'],
			},
		},
	},
	dto: {
		create: CreateBankAccountDto,
	},
})
@UseGuards(AuthGuard('jwt'))
@ApiTags('bank-account')
@ApiBearerAuth()
@Controller('banks/account')
export class BankAccountController implements CrudController<BankAccount> {
	constructor(public service: BankAccountService) { }

	@Override()
	@Post()
	@UsePipes(ValidationPipe)
	@ApiResponse({ status: HttpStatus.CREATED })
	@ApiNotFoundResponse({
		description: `
		${notFoundMessage('Bank')}
		${notFoundMessage('Service Provider')}
		`,
	})
	@ApiForbiddenResponse({
		description: forbiddenCreateBankAccountAlreadyExists,
	})
	createOne(
		@ParsedRequest() req: CrudRequest,
		@ParsedBody() dto: CreateBankAccountDto,
	): Promise<BankAccount> {
		return this.service.create(req, dto);
	}
}

@Entity()
export class BankAccount {
	@PrimaryGeneratedColumn('uuid')
	@ApiProperty({ required: false })
	id: string;

	@Column({ type: 'varchar', length: AGENCY_LENGHT, nullable: true })
	@ApiProperty({
		type: String,
		minLength: AGENCY_LENGHT,
		maxLength: AGENCY_LENGHT,
	})
	@IsString()
	agency: string;

	@Column({ type: 'varchar', length: ACCOUNT_LENGHT, nullable: true })
	@ApiProperty({
		type: String,
		maxLength: ACCOUNT_LENGHT,
	})
	@IsString()
	account: string;

	@Column({ type: 'enum', enum: AccountType })
	@ApiProperty({
		type: AccountType,
		enum: AccountType,
	})
	accountType: AccountType;

	@ManyToOne((type) => Bank, (bank) => bank.bankAccounts, {
		cascade: true,
		eager: true,
		onDelete: 'CASCADE',
	})
	@ApiProperty({ type: Bank })
	bank: Bank;

	@OneToOne((type) => ServiceProvider, (serviceProvider) => serviceProvider.bankAccount, {
		cascade: true,
		eager: true,
		onDelete: 'CASCADE',
	})
	@JoinColumn()
	@ApiProperty({ type: () => ServiceProvider })
	serviceProvider: ServiceProvider;

	@Column({ type: 'varchar', length: DOCUMENT_LENGTH, nullable: true })
	@ApiProperty({
		type: String,
		maxLength: DOCUMENT_LENGTH,
	})
	document: string;

	@Column({ type: 'varchar', length: MAX_LAST_NAME_LENGTH, nullable: true })
	@ApiProperty({
		type: String,
		minLength: MIN_NAME_LENGTH,
		maxLength: MAX_LAST_NAME_LENGTH,
	})
	@Length(MIN_NAME_LENGTH, MAX_LAST_NAME_LENGTH)
	name: string;

	fromDto(dto: CreateBankAccountDto): BankAccount {
		this.account = dto.account;
		this.accountType = dto.accountType;
		this.agency = dto.agency;
		this.bank = new Bank();
		this.bank.id = dto.bankId;
		this.serviceProvider = new ServiceProvider({});
		this.serviceProvider.id = dto.serviceProviderId;
		return this;
	}
}

**Comment by zMotivat0r** [comment]
you need explicitly set [type](https://github.com/nestjsx/crud/wiki/Controllers#params) for your `id` as `uuid`
