### ISSUE TITLE
DTO Type Incompatible with Crud Type

### ISSUE THREAD

**Issue by bestickley** [nestjsx/crud#554]
Hello, how can I use a DTO that is incompatible with the Crud Type? For example:

```
// appRequest.entity.ts
@Entity({ name: "AppRequest" })
export class AppRequest {
  @Column("int)
  id: number;
  @Column("int")
  updatedById?: number;
}
```
```
// appRequest.dto.ts
export class UpdateAppRequestDTO {
   id: number;
   updatedById: number;
}
```
```
// appRequest.controller.ts
@Crud({
  dto: {
    update: UpdateAppRequestDTO
  },
  model: {
    type: AppRequest
  },
})
@Controller("app-request")
export class AppRequestController implements CrudController<AppRequest> {
 constructor(public service AppRequestService) {}
}
```
```
// appRequest.service.ts
@Injectable()
export class AppRequestService extends TypeOrmCrudService<AppRequest> {
  constructor( @InjectRepository(AppRequest) private readonly appRequestRepository: Repository<AppRequest>) {
    super(appRequestRepository);
  }
  async updateOne(req: CrudRequest, dto: UpdateAppRequestDTO) {
    super.updateOne(req, dto);
  }
}
```

Here is the error: 
```
src/appRequest/appRequest.controller.ts:27:14 - error TS2420: Class 'AppRequestController' incorrectly implements interface 'CrudController<AppRequest>'.
  The types of 'service.updateOne' are incompatible between these types.
    Type '(req: CrudRequest, dto: UpdateAppRequestDTO) => Promise<AppRequest>' is not assignable to type '(req: CrudRequest, dto: AppRequest) => Promise<AppRequest>'.
      Types of parameters 'dto' and 'dto' are incompatible.
        Type 'AppRequest' is not assignable to type 'UpdateAppRequestDTO'.
          Types of property 'appRequestRoles' are incompatible.
            Type 'AppRequestRole[]' is not assignable to type 'UpdateAppRequestRoleDTO[]'.
              Type 'AppRequestRole' is not assignable to type 'UpdateAppRequestRoleDTO'.
                Types of property 'updatedById' are incompatible.
                  Type 'number | undefined' is not assignable to type 'number'.
                    Type 'undefined' is not assignable to type 'number'.
```

I know I can fix this by making the types match, but that doesn't accurately reflect the logic I'm trying to implement. Must I create a custom route?

**Comment by bestickley** [comment]
Boiled down question: why does the DTO structure have to match the entity structure?

**Comment by zMotivat0r** [comment]
@bestickley you forgot to apply `@Override` decorator to the `updateOne` method

**Comment by bestickley** [comment]
@zMotivat0r, correct. do you have a suggested solution?

**Comment by zMotivat0r** [comment]
>do you have a suggested solution?
yes, one suggestion - change `updatedById?: number;` to `updatedById: number;` in your entity

**Comment by bestickley** [comment]
The ultimate solution to my question is to enable a capability where one can pass a `CreateEntityDTO` or `UpdateEntityDTO` to the `TypeOrmCrudService` like `TypeOrmCrudService<UserEntity, CreateUserEntity, UpdateUserEntity>` but in terms of priorities that's probably pretty low.
For others reading this issue, you'll need to add an additional method on your service that's not one of the reserved names.

**Comment by tbrannam** [comment]
The `CrudController` has methods which differ a bit from the equivalent methods in `TypeOrmCrudService`. `TypeOrmCrudService` declares that the dto is required only to be a `DeepPartial`.  Adding the following declaration into your project would reflect what's actually happening.   the `crud` package doesn't have a dependency on `typeorm` - so it doesn't feel appropriate to define this in the `crud` package.   But I do think that it makes sense to extend `CrudController` from inside `@nestjsx/crud-typeorm`

```
declare module '@nestjsx/crud' {
  interface CrudController<T> {
    createOneBase?(req: CrudRequest, dto: DeepPartial<T>): Promise<T>;
    createManyBase?(req: CrudRequest, dto: CreateManyDto<DeepPartial<T>>): Promise<T[]>;
    updateOneBase?(req: CrudRequest, dto: DeepPartial<T>): Promise<T>;
    replaceOneBase?(req: CrudRequest, dto: DeepPartial<T>): Promise<T>;
  }
}
```
