### ISSUE TITLE
Id of entity with UUID type instead of Number not working

### ISSUE THREAD

**Issue by basvdijk** [nestjsx/crud#56]
When I define my model in TypeORM as:
```
@Entity()
export class User {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ default: false })
  isActivated: boolean;
}
```

I can use `POST` without any problem. However when I use `PATCH` it is expecting the `id` to be a numeric string:
```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Validation failed. Param 'id': numeric string is expected"
}
```

The body I've sent is:

```
{
    "id": "6aca65b8-ac87-4db8-a492-f4461655b5fa",
    "isActivated": true
}
```

**Comment by zMotivat0r** [comment]
Please read [this](https://github.com/nestjsx/crud#params-options) doc section.

**Comment by zMotivat0r** [comment]
so in your case, you should add this to the `CrudOptions`:
```js
{
  params: {
    id: 'uuid';
  }
}
```

**Comment by basvdijk** [comment]
Thanks! 👍

**Comment by sandeshgb** [comment]
can you be more specific, i.e. in exactly which file to do the above mentioned modifications!
I'm using Get call but as my ID is uuid its giveing me error "Invalid param id. Number expected"

**Comment by mehmet-erim** [comment]
New version configuration is like this:
```ts
@Crud({
  model: {
    type: YourEntity,
  },
  params: {
    id: {
      type: 'uuid',
      primary: true,
      field: 'id',
    },
  },
})
```

**Comment by RicardofVallejo** [comment]
In our case it was because we extended the get method

  ```
@Override('getOneBase')
  getOneAndDoStuff(
    @ParsedRequest() req: CrudRequest,
  ) {
    return this.base.getOneBase(req);
  }
```
