### ISSUE TITLE
Versioning support

### ISSUE THREAD

**Issue by jakemonton** [nestjsx/crud#564]
Hi, I'm currently creating a RESTful API using NestJS & NestJS CRUD. Is there an easier way to implement versioning for my API?

Example:
`/v1/users`
`/v2/users`

I know that NestJS has [Global prefix](https://docs.nestjs.com/faq/global-prefix#global-prefix) which you can use to specify the version. But what if I wanted to support backward compatibility for my API?

Any suggestion would be great :) Thanks!

**Comment by zMotivat0r** [comment]
>I know that NestJS has Global prefix which you can use to specify the version. But what if I wanted to support backward compatibility for my API?

In that case, you run several API apps with different versions. And yeah, this question has nothing to do with CRUD lib
