### ISSUE TITLE
Service functions undefined when using the @Crud () decorator, the service with TypeOrmCrudService.

### ISSUE THREAD

**Issue by MikhailRommulo** [nestjsx/crud#577]
The name of the auto injectable service, needs to be the same as that of the documentation to work correctly, otherwise the service functions are undefined.
below use to work correctly
`constructor(public service: UserService) {}`
use to have service error
`constructor(public userService: UserService) {}`

**Comment by zMotivat0r** [comment]
This was discussed earlier. Please see in closed issues.
