### ISSUE TITLE
Example project link is broken in docs

### ISSUE THREAD

**Issue by basvdijk** [nestjsx/crud#58]
In the readme at https://github.com/nestjsx/crud#example-project there is a "here" link pointing to https://github.com/nestjsx/crud/tree/master/restful/integration/typeorm which doesn't exist anymore.

**Comment by GillesWHC** [comment]
@basvdijk I think [this](https://github.com/nestjsx/crud/tree/master/integration/typeorm) is the example you're looking for. Sorry for the late reply.

**Comment by basvdijk** [comment]
Thanks! Maybe update the url in the docs as well?
