### ISSUE TITLE
Why nestjs-crud recipe was removed from nestjs official documentation ?

### ISSUE THREAD

**Issue by rahpuser** [nestjsx/crud#584]
I have a memory that I saw nestjsx/crud project suggested by the official Nestjs documentation as a way to go to easy crud creation. However, now that I'm looking for it, I can't find any reference in the official nestjs documentation for this project.

Do you guys have an idea of why the project was removed or is not any more in the recipes list ?

**Comment by zMotivat0r** [comment]
You'd better ask @kamilmysliwiec

**Comment by kamilmysliwiec** [comment]
Unfortunately, having a dedicated chapter in the documentation led to the wrong assumption that using this particular package is an official, recommended way of building CRUD applications with NestJS. This chapter was ranked #1 in Google when someone searched for "nestjs crud"  causing that often the very first page of new users visiting the documentation was this page, creating the impression that this is the only suitable & official way to create REST apps.
