### ISSUE TITLE
Scheduled Releases

### ISSUE THREAD

**Issue by tbrannam** [nestjsx/crud#598]
There have been a couple bug fixes that have been merged in the last couple of months.  Do you have an expectation for when you will tag and build a new release?

**Comment by tbrannam** [comment]
@zMotivat0r any plans on a release soon?

**Comment by zMotivat0r** [comment]
@tbrannam I'm really sorry for such a bad inconsistency in releases. There will be a release this month for sure

**Comment by tbrannam** [comment]
This is a great library - but it appears that it's stalled which makes it less attractive than it once was.  I'd be interested to hear what we can expect in 2021 with nestjsx/crud.  Are there plans to open the project to additional maintainers to help you deal with Pull-Requests and/or releases?
