### ISSUE TITLE
nested filter not working

### ISSUE THREAD

**Issue by MSharifi78** [nestjsx/crud#60]
consider this schema.
`color:{
	...,
	car: {
		id: 1,
		.
		.
		.
	}
}
`

when I query `URL/color?join=car`
it's give me joined objects but when I add the filter param to get color with specific car Id by query `url/color?join=car&filter=car.id||eq|1` I get response `{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Invalid column name 'car.id'"
}`

**Comment by Diluka** [comment]
Do you set the options?
```ts
@Crud(Color, {
  options: {
    join: {
      car: {}
    }
  }
})
```

**Comment by MSharifi78** [comment]
yes I do, I set it as the document said. inside service class I define a protected options variable.
and as I mentioned I get the joiend response when I query without filter

**Comment by Diluka** [comment]
Could you provide a minimal repo to reproduce this issue?

**Comment by MSharifi78** [comment]
Sure
here it is: https://github.com/MSharifi78/nestjsx-crud

**Comment by Diluka** [comment]
Oh, the nested filter feature is adding in `3.x` and it is only support nest version above `6`

**Comment by Diluka** [comment]
You need to upgrade to use this new feature. Or you can fork and downgrade using `next` branch, this branch shall support install from github
```json
{
"dependencies": {
    "@nestjs/common": "^6",
    "@nestjs/core": "^6",
    "@nestjs/platform-express": "^6.0.5",
    "@nestjs/swagger": "^3",
    "@nestjs/typeorm": "^6",
    "@nestjsx/crud": "^3",
    "class-transformer": "^0.2.0",
    "class-validator": "^0.9.1",
    "mysql": "^2.16.0",
    "reflect-metadata": "^0.1.12",
    "rimraf": "^2.6.2",
    "rxjs": "^6.2.2",
    "typeorm": "^0.2.15-rc.2",
    "typescript": "^3.0.1"
  },
  "devDependencies": {
    "@nestjs/testing": "^6",
    "@types/express": "^4.16.0",
    "@types/jest": "^24",
    "@types/node": "^10.7.1",
    "@types/supertest": "^2.0.5",
    "jest": "^24",
    "nodemon": "^1.18.3",
    "prettier": "^1.14.2",
    "supertest": "^3.1.0",
    "ts-jest": "^24",
    "ts-loader": "^4.4.2",
    "ts-node": "^7.0.1",
    "tsconfig-paths": "^3.5.0",
    "tslint": "5.11.0"
  }
}
```
