### ISSUE TITLE
Improving generated swagger documentation

### ISSUE THREAD

**Issue by yann510** [nestjsx/crud#618]
It would be great if the generated documentation would have proper responses being returned in the examples.

![image](https://user-images.githubusercontent.com/6068943/96388926-45d1ed00-117a-11eb-8ab2-042eeee7aa67.png)

Also, for the requests, it's very hard to know what is actually possible. You need to go look at the defined schemas at the bottom of the page and even then, they do not seem to be properly generated.

![image](https://user-images.githubusercontent.com/6068943/96388952-82054d80-117a-11eb-9bb0-82677e416d45.png)

Any idea as to how we can improve this? I'd be happy to help.

**Comment by tbrannam** [comment]
My application has these things - I suspect you are missing something either in your controllers or the swagger setup in your app?

**Comment by yann510** [comment]
Is your application open-source?
If so a link to it would be amazing so I can learn what I'm doing wrong!

**Comment by tbrannam** [comment]
It is not, but I'd look at yours if you had it in github or something like
that.

**Comment by yann510** [comment]
It is in fact an open-source project, I really appreciate you giving me a hand :)

https://github.com/chocolat-chaud-io/stator
you can find the nest application under `apps/api`

**Comment by tbrannam** [comment]
I don't see anything super obviously wrong in your code - my only thought is perhaps the Swagger DocumentBuilder can't resolve the path for `Todo` while Typescript can...  I'd suggest doing a test by copying your model and referencing it as a local module.

**Comment by yann510** [comment]
Ok, thank you for taking a look. I will try doing that.

**Comment by yann510** [comment]
For anyone interested, here is how I managed to solve the issue: https://github.com/chocolat-chaud-io/stator/pull/135
The problem was caused by the fact the schemas were not loaded automatically.
