### ISSUE TITLE
Nested resources

### ISSUE THREAD

**Issue by AlexandreKueny** [nestjsx/crud#65]
I have entity relations:
- one User => many Reservations
- one Reservation => many Borrowing

I have `GET /users/:user/reservations/:reservation/borrowings` endpoint.

BorrowingsController is looking for a field named `user` in the Borrowing entity, which doesn't exist. So I get `Invalid column name 'user'` error.

How can I achieve this ?

**Comment by zMotivat0r** [comment]
use this https://github.com/nestjsx/crud/wiki/Controllers#params
