### ISSUE TITLE
Entity validation does not work unless dto option is specified

### ISSUE THREAD

**Issue by MarcMogdanz** [nestjsx/crud#671]
I have an entity `Product` which has an `age` property that needs to be set and the value needs to be at least 5.

Entity:

```typescript
@Entity()
export class Product extends BaseEntity {
  @PrimaryGeneratedColumn("uuid")
  id: string;

  @Column()
  @IsNotEmpty()
  @Min(5)
  age: number;
}
```

When I use the following controller and try to create a product with an `age: 2` it will not throw a validation error and create the entry in the DB.

```typescript
@Crud({
  model: {
    type: Product,
  },
  routes: {
    only: [
      "getOneBase",
      "replaceOneBase",
      "deleteOneBase",
      "getManyBase",
      "createOneBase",
    ],
  },
  params: {
    ...defaultParamsOptions,
  },
})
@ApiTags("Product")
@Controller("products")
export class ProductController implements CrudController<Product> {
  constructor(
    public service: ProductService
  ) {}
}
```

But when I add the `dto` configuration option to the CRUD decorator and add the `Product` entity as a dto for the create option it does now throw a validation error on the `age` property.

```typescript
@Crud({
  // ...
  dto: {
    create: Product,
  },
})
```

According to the [wiki](https://github.com/nestjsx/crud/wiki/Controllers#request-validation) it should be possible to not need to set the `dto` option when a valid `model: { type: Entity }` is set in the CRUD controller:

> You can provide either create, update, replace DTO in the CrudOptions.dto options or use the following approach.
You can use CrudOptions.model.type as a DTO that describes validation rules. 

My question is now, what am I doing wrong? :)

**Comment by zMotivat0r** [comment]
hi,

wiki says:
```You can use CrudOptions.model.type as a DTO that describes validation rules. We distinguish body validation on create and update methods. This was achieved by using validation groups.```
So, in order to use an entity as a dto you should use CREATE / UPDATE validation group in each validation decorator
