### ISSUE TITLE
GetManyBase return schema is different than the return value when no parameters are sent

### ISSUE THREAD

**Issue by Adi1231234** [nestjsx/crud#674]
'GetManyBase' route return schema is different than the return value when no parameters are sent.
The return value is an array while the return schema is an object that looks like:
`{
  "data": [],
  "count": 0,
  "total": 0,
  "page": 0,
  "pageCount": 0
}`

I would expect the return value to be deterministic since I will not be able to parse it in the same way when I do not send parameters or at least the schema will be correct in all cases.

**Comment by greenking19** [comment]
I have the same problem, please how did you solve it
