### ISSUE TITLE
Is there anyway to disable joins and filters when use nestjs CRUD ?

### ISSUE THREAD

**Issue by AlexSun98** [nestjsx/crud#707]
hi all, 

I have a few questions to ask. 

1. Is there any way to disable query's joins and filters at get endpoints when use nestjs with CRUD ?

2. Is there any way to customize swagger doc such as toggling query's filter and join feature's doc?

3.  Does curd TypeOrm libaray provides a query retry when there is a db connection issue? e.g. db connection takes too long. existing conenction is killed right befure executing a query against db.

Thanks!

**Comment by hakimio** [comment]
1. Yes. [Query](https://github.com/nestjsx/crud/wiki/Controllers#query)
2. You can customize the model schema shown in swagger docs by using `@ApiProperty()` and `@ApiPropertyOptional()` decorators, but you can't customize the default list of query parameters.
3. No, that's out of library scope.
