### ISSUE TITLE
@SetMetadata is broken in controller scope

### ISSUE THREAD

**Issue by jakobrosenberg** [nestjsx/crud#71]
The below example should apply metadata to all methods in the controller scope, but for some reason it doesn't.

```
@SetMetadata('roles', ['admin', 'editor'])
@Crud(establishment)
@Controller('establishment'){
  ...
}
```

https://github.com/nestjs/nest/issues/2027

**Comment by zMotivat0r** [comment]
https://github.com/nestjs/nest/blob/5e8fd1e6902f0a4581b3113f699cf92cf510f2ee/packages/common/decorators/core/set-metadata.decorator.ts#L7-L17

I don't think that it `should apply metadata to all methods`. It's clear from its source code that shouldn't

**Comment by jaredatron** [comment]
this worked for me 

```ts
  async canActivate(context: ExecutionContext) {
    const classFeatureFlags = this.reflector.get<string[]>(featureFlagsMetadataKey, context.getClass()) || [];
    const methodFeatureFlags = this.reflector.get<string[]>(featureFlagsMetadataKey, context.getHandler()) || [];
    const featureFlags = new Set([...classFeatureFlags, ...methodFeatureFlags]);
  }
```
