### ISSUE TITLE
[HELP] Is it possible to find what entity was used to generate POST, GET and PATCH in a endpoint?

### ISSUE THREAD

**Issue by and-dutra** [nestjsx/crud#72]
Hello everyone,

Is it possible to find which entity was used to generated the currently accessed endpoint?

For example:

I create a controller using 

> @Crud(Hero)
> @Controller('heroes')
> export class heroController{} 

Now i want to get what entity was used to create the GET, POST and PATCH when a request is made for: http://example.com/heroes, using a global middleware, is that possible ?

Thanks in advance for any help.

**Comment by jakobrosenberg** [comment]
Have you looked at ``context.getClass()``?

https://docs.nestjs.com/interceptors
