### ISSUE TITLE
Idea about file upload

### ISSUE THREAD

**Issue by zerox12311** [nestjsx/crud#74]
I think can create a CRUD with support file upload.
It will upload file to defined location and auto save file path to database.

**Comment by zMotivat0r** [comment]
Actually, I don't think that file uploading has anything to do with the CRUD operation. So I will close this issue unless there are some good examples from other crud frameworks. It's appreciated if you could provide some of those. Thanks!

**Comment by loicgeek** [comment]
> I think can create a CRUD with support file upload.
> It will upload file to defined location and auto save file path to database.

Did you handle that ?

**Comment by marcovelarde** [comment]
A god example of this feature (not a js or ts framework) is django rest framework. It has a class called FileField that allow save a file in specific directory and save the relative path in the database.

Its ORM do this setting up a media dir and when serialize data, concatenate the host with the relative path.

Its useful for applications such as an ecommerce, allowing better images management or any other file type.

<a href="https://docs.djangoproject.com/en/3.0/ref/models/fields/#filefield" target="_blank">Here</a> is the documentation

Its possible include this feature in future releases?

**Comment by loicgeek** [comment]
hey bro, its pretty easy , using multer you can create and interceptor to upload the file and override the controller method which is concerned , `import { Controller, UseGuards, Req, Param } from '@nestjs/common';
import {
  CrudController,
  Crud,
  CrudOptions,
  Override,
  ParsedRequest,
  CrudRequest,
  ParsedBody,
} from '@nestjsx/crud';
import { ResourceItem } from '../entities/resource_item.entity';
import { ResourceItemsService } from './resource-items.service';
import { FileInterceptor } from '@nestjs/platform-express';
import { extname } from 'path';
import { diskStorage } from 'multer';
import { ApiTags, ApiBearerAuth } from '@nestjs/swagger';
import { AuthGuard } from '@nestjs/passport';
import { checkOwnerChip } from '../../app.utils';

const itemsCrudOptions: CrudOptions = {
  model: {
    type: ResourceItem,
  },
  query: {
    join: {
      resourceItems: {
        eager: true,
      },
    },
  },
  routes: {
    createOneBase: {
      interceptors: [
        FileInterceptor('file', {
          storage: diskStorage({
            destination: './uploads/images',
            filename: (req, file, cb) => {
              const randomName = Array(32)
                .fill(null)
                .map(() => Math.round(Math.random() * 16).toString(16))
                .join('');
              return cb(null, `${randomName}${extname(file.originalname)}`);
            },
          }),
        }),
      ],
    },
  },
};
@Controller('items')
@Crud(itemsCrudOptions)
@ApiTags('items')
export class ResourceItemsController {
  constructor(public service: ResourceItemsService) {}

  get base(): CrudController<ResourceItem> {
    return this;
  }

  @Override()
  @UseGuards(AuthGuard('jwt'))
  @ApiBearerAuth()
  async replaceOne(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: ResourceItem,
    @Req() rq,
@UploadedFile() file,
    @Param('id') id: string,
  ) {
    await checkOwnerChip<ResourceItem>(this.service, rq.user, id);
    dto.bgImage = file.filename;
    return this.base.createOneBase(req, dto);
  }

`

**Comment by loicgeek** [comment]
I wrote a utils class to facilitate this , 

```

import { FileInterceptor, FilesInterceptor } from '@nestjs/platform-express';

import { diskStorage } from 'multer';
import { extname } from 'path';

export class FileUploadingUtils {
  static singleFileUploader(name: string) {
    return FileInterceptor(name, {
      storage: diskStorage({
        destination: './uploads/images',
        filename: (req, file, cb) => {
          const randomName = Array(32)
            .fill(null)
            .map(() => Math.round(Math.random() * 16).toString(16))
            .join('');
          return cb(null, `${randomName}${extname(file.originalname)}`);
        },
      }),
    });
  }

  static multipleFileUploader(name: string, maxFileNumber: number = 20) {
    return FilesInterceptor(name, maxFileNumber, {
      storage: diskStorage({
        destination: './uploads/images',
        filename: (req, file, cb) => {
          const randomName = Array(32)
            .fill(null)
            .map(() => Math.round(Math.random() * 16).toString(16))
            .join('');
          return cb(null, `${randomName}${extname(file.originalname)}`);
        },
      }),
    });
  }
}

```

and in your controller . 

```
const itemsCrudOptions: CrudOptions = {
  model: {
    type: ResourceItem,
  },
  query: {
    join: {
      images: {},
    },
  },
  routes: {
    createOneBase: {
      interceptors: [FileUploadingUtils.multipleFileUploader('images')],
    },
  },
};

...



  @Override()
  createOne(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: ResourceItem,
    @UploadedFiles() images: any[],
  ) {
    dto.images = [];
    images.forEach(i => {
      dto.images.push(new ImageItem(i.filename));
    });
    return this.base.createOneBase(req, dto);
  }
```

**Comment by windht** [comment]
@loic

> I wrote a utils class to facilitate this ,
> 
> ```
> 
> import { FileInterceptor, FilesInterceptor } from '@nestjs/platform-express';
> 
> import { diskStorage } from 'multer';
> import { extname } from 'path';
> 
> export class FileUploadingUtils {
>   static singleFileUploader(name: string,dest:string='./uploads/images',) {
>     return FileInterceptor(name, {
>       storage: diskStorage({
>         destination: dest,
>         filename: (req, file, cb) => {
>           const randomName = Array(32)
>             .fill(null)
>             .map(() => Math.round(Math.random() * 16).toString(16))
>             .join('');
>           return cb(null, `${randomName}${extname(file.originalname)}`);
>         },
>       }),
>     });
>   }
> 
>   static multipleFileUploader(name: string,dest:string='./uploads/images', maxFileNumber: number = 20) {
>     return FilesInterceptor(name, maxFileNumber, {
>       storage: diskStorage({
>         destination: dest,
>         filename: (req, file, cb) => {
>           const randomName = Array(32)
>             .fill(null)
>             .map(() => Math.round(Math.random() * 16).toString(16))
>             .join('');
>           return cb(null, `${randomName}${extname(file.originalname)}`);
>         },
>       }),
>     });
>   }
> }
> ```
> 
> and in your controller .
> 
> ```
> const itemsCrudOptions: CrudOptions = {
>   model: {
>     type: ResourceItem,
>   },
>   query: {
>     join: {
>       images: {},
>     },
>   },
>   routes: {
>     createOneBase: {
>       interceptors: [FileUploadingUtils.multipleFileUploader('images')],
>     },
>   },
> };
> 
> ...
> 
> 
> 
>   @Override()
>   createOne(
>     @ParsedRequest() req: CrudRequest,
>     @ParsedBody() dto: ResourceItem,
>     @UploadedFiles() images: any[],
>   ) {
>     dto.images = [];
>     images.forEach(i => {
>       dto.images.push(new ImageItem(i.filename));
>     });
>     return this.base.createOneBase(req, dto);
>   }
> ```

Hi @loicgeek How are we forming requests in the frontend using this interceptors with other fields preserved?

With form-data in postman it is giving me:
```
{
    "statusCode": 400,
    "message": "Unexpected token - in JSON at position 0",
    "error": "Bad Request"
}
```

**Comment by FeliIsra** [comment]
Does it works ? someone test it ? What about other files that are not images ?
