### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by oSethoum** [nestjsx/crud#762]
Hello developers, first of all thank you for such a great package to ease the creation of crud API, I have several questions regarding the this package, which are : 
- Is the package still maintained ?  
- Will you add a repo for examples to so many cases that are hard to handle such as nested queries in Many-To-Many relationship ? 
- Where can we find the most active community for this package (Discord, Slack etc...) where developers who use this packages can share their knowledge and ask or offer help to others ?

Thank You in advance for your kind responses.

**Comment by rewiko** [comment]
https://github.com/nestjsx/crud/issues/710

**Comment by oSethoum** [comment]
@rewiko  Happy to hear that this lib isn't gonna die, looking forward for the new release and hoping that it will officially join nestjs.
