### ISSUE TITLE
swagger description is too long

### ISSUE THREAD

**Issue by Diluka** [nestjsx/crud#79]
some ways to make it short
1. support custom swagger description
2. make it short like using url instead of large text 
3. just an options to disable them all

**Comment by roland-chernov-akvelon** [comment]
I love this idea. By the way, currently HTML tags are used for descriptions but when Swagger metadata is used for API client generation ([swagger-api/swagger-codegen](https://github.com/swagger-api/swagger-codegen)) it produces not very good descriptions :slightly_frowning_face:

![html-tags-in-autocompletion](https://user-images.githubusercontent.com/33692429/59847488-4d596a00-936b-11e9-90c5-c3d1f878b4c3.png)

That would be nice to have descriptions without HTML tags or be able to customize them.

**Comment by Diluka** [comment]
https://gist.github.com/Diluka/8292fced132ff97aa6f04ed5e19a3155
I make a decorator to change large English doc into short Chinese one and wrapped some frequently used decorators. Maybe helps

**Comment by roland-chernov-akvelon** [comment]
I'm using something similar but to only extract the first sentence from default descriptions:

```typescript
import { Swagger } from '@nestjsx/crud/lib/crud';
import { BaseRouteName } from '@nestjsx/crud/lib/types';

function extractShortDescription(html: string): string {
  const match = html.match(/<h4>(.*?)</h4>/i); // extract description
  if (!match) {
    return html;
  }
  return match[1].replace(/<\/?.*?>/g, ''); // remove any HTML tags from description
}

export function ApiShortCRUDMeta(): MethodDecorator {
  return (controller, name: BaseRouteName) => {
    const defaultHtmlMeta = Swagger.getParams(controller[name]);
    const meta = defaultHtmlMeta.map(paramMeta => ({
      ...paramMeta,
      description: paramMeta.description
        ? extractShortDescription(paramMeta.description)
        : paramMeta.description,
    }));
    Swagger.setParams(meta, controller[name]);
  };
}
```
