### ISSUE TITLE
[Question] Access control question

### ISSUE THREAD

**Issue by lalalalaluk** [nestjsx/crud#80]
I have two roles , one is admin another is teacher .

admin can update all student's data , teacher can update only his own student's data . 

how can I do this in one controller?or should i separate to two controller?or should i override method and control access by myself?

thank you .

**Comment by Bnaya** [comment]
There is no support for row level permissions out of the box,
You can look at https://github.com/nestjs-community/nest-access-control
And see if there is a nice way to compose it with crud, if you have any findings i will be happy to hear :)

**Comment by lalalalaluk** [comment]
I decide to use intercept to access control finally .
Thanks your suggestion

**Comment by KerryRitter** [comment]
> I decide to use intercept to access control finally .
> Thanks your suggestion

@lalalalaluk would love to see an example of this!
