### ISSUE TITLE
Just wanted to say fuck Ukraine

### ISSUE THREAD

**Issue by MRezaBaiat** [nestjsx/crud#800]
This much of blue and yellow in your project made me throw up , where were you when the USA killed more than 100 million people all around the world ? where are you now that israel regime is killing palestinians or saudi killing yemenis every day ? or when the american terrorists were killing millions of iraqis and afghan people ? where were you when 60 countries including europe and terrorist states went to a war against Iran 40 years ago (and lost! which is why you don't know about the only real World War) ? 
How about the terrorists made by the states like taliban , isis , al qaeda , saddam and.... ?
Oh you didnt see them ? then you shut your mouth , Ukrain got what it deserved for being a puppet
And i am not a russian

Best wishes

**Comment by imnotjames** [comment]
What you've just said is one of the most insanely idiotic things I have ever heard. At no point in your rambling, incoherent response were you even close to anything that could be considered a rational thought. Everyone in this room is now dumber for having listened to it.

**Comment by MRezaBaiat** [comment]
it is not a thought , it is history
