### ISSUE TITLE
Doc error

### ISSUE THREAD

**Issue by lalalalaluk** [nestjsx/crud#82]
hello everyone

i found some error in doc

![image](https://user-images.githubusercontent.com/6902963/57918828-21f5e200-78ca-11e9-9b3c-c7abc36a7bf5.png)

```
  @Override('updateOneBase')
  coolFunction() {
    @ParsedParams() params,
    @ParsedBody() body: Hero,
  } {
    return this.base.updateOneBase(params, body);
  }
```

should be

```
  @Override('updateOneBase')
  coolFunction
    @ParsedParams() params,
    @ParsedBody() body: Hero,
  ){
    return this.base.updateOneBase(params, body);
  }

thanks
```

**Comment by fwoelffel** [comment]
```ts
@Override('updateOneBase')
coolFunction(
  @ParsedParams() params,
  @ParsedBody() body: Hero,
){
  return this.base.updateOneBase(params, body);
}
```

Would be better, you missed a round bracket.
You should submit a PR to fix it :wink: I'd rather like @zMotivat0r to have a look at more fundamental issues than ones such as this.
