### ISSUE TITLE
[question] DTO question

### ISSUE THREAD

**Issue by lalalalaluk** [nestjsx/crud#84]
In @Crud decorator 
![image](https://user-images.githubusercontent.com/6902963/58537473-864b6680-8225-11e9-92dd-fda7c6f7abd5.png)

i put entity with class-validator it works
but when i put dto with class-validator it does nothing
My dto looks like 
![image](https://user-images.githubusercontent.com/6902963/58537634-d4f90080-8225-11e9-8815-7cb31eb9cec4.png)

Is there any mistake i made?
thank you very much

**Comment by Diluka** [comment]
currently, `crud` is only working with `typeorm` entities. Your dto is not a legal entity. It doesn't have any columns.

**Comment by luqezman** [comment]
News? is possible having separated DTO?

**Comment by zMotivat0r** [comment]
@luqezman yes, starting from [v4.3.0](https://github.com/nestjsx/crud/blob/master/CHANGELOG.md#features-2). Please be advised to read the docs
