### ISSUE TITLE
shall use leftJoin by default and support on clause

### ISSUE THREAD

**Issue by Diluka** [nestjsx/crud#98]
https://github.com/nestjsx/crud/blob/35acb442c62cdebea7fd33f5c1e9cf1dec31d539/packages/crud-typeorm/src/typeorm-crud.service.ts#L335-L344

shall use `leftJoin` by default and use `innerJoin` by config
see `sequelize` options `include.required` behavior

If the relation can be set `NULL`, `innerJoin` will break the query.

refer: http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-findAll
> Name | Type | Attribute | Description
> -- | -- | -- | --
> options.include[].required | boolean | optional | If true, converts to an inner join, which means that the parent model will only be loaded if it has any matching children. True if include.where is set, false otherwise.

**Comment by zMotivat0r** [comment]
Ok, let's make it to be `leftJoin` by default, and add `required: boolean` as an option.
@Diluka would you like to make a PR? :) just asking. I can do it on my own

**Comment by Diluka** [comment]
```ts
export type QueryJoin = {
  field: string;
  select?: QueryFields;
  required?: boolean; // <-- add here?
  on?: string; // <-- maybe this together?
};
```
You do this PR is better. I need to take the time to familiarize myself with this new architecture.

When using left join and the relation can be set `null`, the same condition put in `on` or `where` can be different result.

p.s. I feel that it will become more and more complicated here.

**Comment by macchie** [comment]
UP! We had the same problem here :D

**Comment by macchie** [comment]
> @Diluka @macchie this will have a high priority on the next release.

thanks! Great project!

**Comment by Diluka** [comment]
does this related to #31 ? @zMotivat0r

**Comment by zMotivat0r** [comment]
yep

**Comment by MeMeMax** [comment]
Is it correct that I can´t get e.g. only the data of the currently logged in user by now with the config options given or am I missing anything?

**Comment by sergak01** [comment]
UP! I have the same problem!

**Comment by Bnaya** [comment]
See possible workaround:
https://github.com/nestjsx/crud/issues/31#issuecomment-480754565

**Comment by cuni0716** [comment]
Not released yet @zmotivator?

**Comment by codepushr** [comment]
Has the `on=` config been ignored? I think this might be useful nevertheless.
